### PR TITLE
Fix javadoc warnings when building gradle plugin

### LINKED ISSUE #280: Fix :javadoc warnings when building gradle plugin
There's a lot of them and they're ugly

### PR DESCRIPTION
**Pull request by TadCordle**
Fixes #280 

Although we may want to look into this more, and either fix all the warnings by fixing our javadocs, or limit the type of warnings that's suppressed (more options here: https://gist.github.com/hekar/62772af5b0fe0b6731bb)

### CODE REVIEW

**Comment by coollog** [comment]
Yeah, we probably don't want to disable doclint completely since there's a lot of useful checks in there. If we want to fix that issue, we should probably just fix all the warnings.

**Comment by TadCordle** [comment]
I think I'll work on that then. Fixing javadocs has the added benefit of getting me more familiar with the whole codebase as well.

File: jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerContextGenerator.java [hunk 1]
```diff
@@ -60,31 +60,54 @@ public DockerContextGenerator(SourceFilesConfiguration sourceFilesConfiguration)
   /**
    * Sets the base image for the {@code FROM} directive. This must be called before {@link
    * #generate}.
+   *
+   * @param baseImage the base image.
+   * @return The {@link DockerContextGenerator} with the base image set.
```
Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerContextGenerator.java]: nit: lowercase for start of `@...` docs and no period

Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerContextGenerator.java]: can also just simplify the `@return` to like `@return this`

File: jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/DirectoryWalker.java [hunk 2]
```diff
@@ -31,21 +31,35 @@
...
       throw new NotDirectoryException(rootDir + " is not a directory");
     }
     this.rootDir = rootDir;
   }
 
-  /** Adds a filter to the walked paths. */
+  /**
+   * Adds a filter to the walked paths.
+   *
+   * @param pathFilter the filter.
```
Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/DirectoryWalker.java]: `filter returns {@code true} if the path should be accepted and {@code false} otherwise`

File: jib-core/src/main/java/com/google/cloud/tools/jib/frontend/HelpfulSuggestions.java [hunk 3]
```diff
@@ -112,7 +112,10 @@ public String none() {
     return messagePrefix;
   }
 
-  /** @return the message containing a suggestion */
+  /**
+   * @param suggestion a suggested fix for the problem described by {@code messagePrefix}
```
Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/frontend/HelpfulSuggestions.java]: I think for here you can actually use `{@link #messagePrefix}`.

File: jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerContextGenerator.java (hunk 1 above)
Comment (TadCordle) [reply jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerContextGenerator.java]: Oh, should we not be using periods? It seems to be 50/50 everywhere so I've been adding them.

Comment (coollog) [reply jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerContextGenerator.java]: Yeah, I believe the style is to only use a period for these block tags if you have a second sentence afterwards. I can't quite find where this convention was stated at though...

File: jib-core/src/main/java/com/google/cloud/tools/jib/image/Image.java [hunk 4]
```diff
@@ -32,36 +32,71 @@
...
     public Builder<T> setEnvironmentVariable(String name, String value) {
       environmentBuilder.add(name + "=" + value);
       return this;
     }
 
-    /** Adds an environment variable definition in the format {@code NAME=VALUE}. */
+    /**
+     * Adds an environment variable definition in the format {@code NAME=VALUE}.
+     *
+     * @param environmentVariableDefinition the string to add
```
Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/image/Image.java]: the *definition* to add?

File: jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageLayers.java [hunk 5]
```diff
@@ -101,12 +114,19 @@ public boolean isEmpty() {
...
+   * @return the layer at the specified index
+   */
   public T get(int index) {
     return layers.get(index);
   }
 
-  /** @return the layer by digest, or {@code null} if not found */
+  /**
+   * @param digest the digest used to retrieve the layer
+   * @return the layer by digest, or {@code null} if not found
```
Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageLayers.java]: the layer *found*?

File: jib-gradle-plugin/build.gradle [hunk 6]
```diff
@@ -98,6 +98,13 @@ tasks.withType(JavaCompile) {
     }
 }
 
+// Fail build on javadoc warnings
+if (JavaVersion.current().isJava8Compatible()) {
```
Comment (coollog) [inline jib-gradle-plugin/build.gradle]: We can just configure this directly on `googleJavaFormat` right?

Comment (coollog) [reply jib-gradle-plugin/build.gradle]: We should also add this for core and maven.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildLogger.java [hunk 7]
```diff
@@ -20,7 +20,6 @@
 
   void error(CharSequence message);
 
-  /** Logs messages as part of normal execution (default log level). */
```
[the remark this answers is not in the document]
Comment (TadCordle) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildLogger.java]: It seemed out of place as the only javadoc'd method, and I thought it was self-explanatory enough to remove. But on second thought, the "default log level" part seems important, so I'll put it back.

[the remark this answers is not in the document]
Comment (coollog) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildLogger.java]: Yea, this is to make sure callers user lifecycle for normal default log messages (compared to the other ones, which will only show if some verbosity is enabled).

File: jib-gradle-plugin/build.gradle (hunk 6 above)
Comment (TadCordle) [reply jib-gradle-plugin/build.gradle]: How (for both of those)?

Comment (coollog) [reply jib-gradle-plugin/build.gradle]: It might not be possible but it looks like the gradle plugin can define options as part of the extension: https://github.com/sherter/google-java-format-gradle-plugin#extended-usage

Comment (coollog) [reply jib-gradle-plugin/build.gradle]: Oh okay that's probably my misunderstanding

File: jib-core/build.gradle [hunk 8]
```diff
@@ -79,6 +79,13 @@ tasks.withType(JavaCompile) {
     }
 }
 
+// Fail build on javadoc warnings
+if (JavaVersion.current().isJava8Compatible()) {
```
Comment (coollog) [inline jib-core/build.gradle]: Is this compatibility check needed? Our codebase is completely in java 8.

File: jib-core/build.gradle [hunk 9]
```diff
@@ -79,6 +79,13 @@ tasks.withType(JavaCompile) {
...
+    tasks.withType(Javadoc) {
+        options.addStringOption('Xwerror', '-quiet')
```
Comment (coollog) [inline jib-core/build.gradle]: What does the `-quiet` do?

File: jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java [hunk 10]
```diff
@@ -57,7 +57,10 @@ public void set(String image) {
     }
   }
 
-  /** @return the {@link ImageReference} parsed from {@code from}. */
+  /**
+   * @param from the image reference string to parse.
+   * @return the {@link ImageReference} parsed from {@code from}.
+   */
   static ImageReference parseBaseImageReference(String from) {
```
Comment (coollog) [inline jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java]: Just noticed these two methods are essentially identical. We could prob just have one method and a second parameter that's the 'parameter name'.

File: jib-core/build.gradle (hunk 9 above)
Comment (TadCordle) [reply jib-core/build.gradle]: I think it's just a hack to fill the second argument of `addStringOption`, since gradle automatically adds the '-quiet' option anyway.

Comment (coollog) [reply jib-core/build.gradle]: It looks like you could possibly try `.addBooleanOption('Xwerror', true)`

https://github.com/gradle/gradle/issues/1393#issuecomment-280287314
