### PR TITLE
Don't fail on main class inference if custom entrypoint

### LINKED ISSUE #3295: After upgrading jib-maven-plugin from 3.0.0 to 3.1.0 entrypoint=INHERIT doesn't ignore mainClass
**Environment**:

- *Jib version:* 3.1.0 (jib-maven-plugin)
- *Build tool:* Maven 3.6.3
- *OS:* Linux

**Description of the issue**:

After updating `jib-maven-plugin` from version `3.0.0` to version `3.1.0` execution of `dockerBuild` goal for container with container.entrypoint=INHERIT configuration option fails with error:

```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.1.0:dockerBuild (docker-image-package) on project javadocs: Main class was not found, perhaps you should add a `mainClass` configuration to jib-maven-plugin -> [Help 1]
```

[README says](https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/README.md#container-object) that entrypoint=INHERIT means mainClass is not taken into account, which seems to be broken in 3.1.0

**Expected behavior**:

After updating 3.0.0 -> 3.1.0 build should succeed because release notes don't say anything about changed behaviour of entrypoint=INHERIT configuration.

**Steps to reproduce**:

1. Add `jib-maven-plugin` configuration from block below with version `3.0.0` into pom.xml:

2. Execute the following command: `mvn package` and Docker image is **built successfully**.

3. Change `jib-maven-plugin` version to `3.1.0`, execute `mvn package` - **build fails** with the following error:
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.1.0:dockerBuild (docker-image-package) on project javadocs: Main class was not found, perhaps you should add a `mainClass` configuration to jib-maven-plugin -> [Help 1]
```

**`jib-maven-plugin` Configuration**: 
```xml
<build>
    <plugins>
      <plugin>
          <groupId>com.google.cloud.tools</groupId>
          <artifactId>jib-maven-plugin</artifactId>
          <version>3.0.0</version> <!-- 3.0.0 works, 3.1.0 fails -->
          <configuration>
            <from>
              <image>nginx:alpine</image>
            </from>
            <to>
              <image>a:b</image>
            </to>
            <container>
              <entrypoint>INHERIT</entrypoint>
            </container>
          </configuration>
          <executions>
            <execution>
              <id>docker-image-package</id>
              <phase>package</phase>
              <goals>
                <goal>dockerBuild</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
    </plugins>
</build>
```

**Log output**: 

```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.1.0:dockerBuild (docker-image-package) on project javadocs: Main class was not found, perhaps you should add a `mainClass` configuration to jib-maven-plugin -> [Help 1]
```

**Additional Information**:

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #3295.

### CODE REVIEW

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java [hunk 1]
```diff
@@ -632,9 +632,19 @@ static JavaContainerBuilder getJavaContainerBuilderWithBaseImage(
...
-            rawConfiguration.getMainClass().orElse(null), projectProperties);
+    String mainClass;
+    try {
+      mainClass =
+          MainClassResolver.resolveMainClass(
+              rawConfiguration.getMainClass().orElse(null), projectProperties);
+    } catch (MainClassInferenceException ex) {
+      if (entrypointDefined) {
+        // We will use the user-given entrypoint, so don't fail.
+        mainClass = "could-not-infer-a-main-class";
```
Comment (mpeddada1) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java:643]: Just a thought, can we call `MainClassResolver#resolveMainClass` only if the entrypoint is not defined?

Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java:643]: If you remember, we always create the arg files whether or not an entrypoint is defined so that people can use them in their custom entrypoint.

Comment (mpeddada1) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java:643]: Oh right, sorry that makes sense.

**Review by mpeddada1 — APPROVED** [review]
