### PR TITLE
BlobPusher must use `from` with `mount`

### LINKED ISSUE #703: Blob Pusher missing required `from` parameter
**Description of the issue**:

In testing #698, I discovered that quay.io rejects our layer pushes with an `INVALID_REQUEST`.

```
Tried to push BLOB for quay.io/briandealwis/foo with digest sha256:8f125ded1b483229a567e48eece98cc8867c2bee55fb73e9cd65ceecc448b7c7 but failed because: unknown: Invalid request | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new: 400 BAD REQUEST
[ERROR] {"errors":[{"code":"INVALID_REQUEST","detail":{},"message":"Invalid request"}]}
```

`BlobPusher` is not fully implementing the [_Cross Repository Blob Mount_](
https://docs.docker.com/registry/spec/api/#pushing-an-image) request which specifies that the `POST` request should have both a `mount` and a `from`.

> To issue a blob mount instead of an upload, a POST request should be issued in the following format:
> ```
> POST /v2/<name>/blobs/uploads/?mount=<digest>&from=<repository name>
> Content-Length: 0
> ```

Pushing to quay.io (#500) still fails due to #601.

### PR DESCRIPTION
**Pull request by briandealwis**
Fixes #703

Changes BlobPusher to take an optional source repository.  If specified, then it will provide the `mount` and `from` when uploading blobs.

With this, we can optimize the `PushBlobStep` to remove the [`checkBlob` before any pushes](https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java#L80) when the source and target images are on the same repository.

Here's an HTTP trace showing that `gcr.io` skips the upload because its found in `distroless/java`.
```
CONFIG: -------------- REQUEST  --------------
POST https://gcr.io/v2/xxx/first/blobs/uploads/?mount=sha256:8f125ded1b483229a567e48eece98cc8867c2bee55fb73e9cd65ceecc448b7c7&from=distroless/java
Accept: 
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: jib 0.9.8-SNAPSHOT jib-maven-plugin Google-HTTP-Java-Client/1.23.0 (gzip)

Jul 27, 2018 4:19:02 PM com.google.api.client.http.HttpRequest execute
CONFIG: curl -v --compressed -X POST -H 'Accept: ' -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: jib 0.9.8-SNAPSHOT jib-maven-plugin Google-HTTP-Java-Client/1.23.0 (gzip)' -- 'https://gcr.io/v2/xxx/flip/first/blobs/uploads/?mount=sha256:8f125ded1b483229a567e48eece98cc8867c2bee55fb73e9cd65ceecc448b7c7&from=distroless/java'
Jul 27, 2018 4:19:02 PM com.google.api.client.http.HttpResponse <init>
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 201 Created
Docker-Distribution-API-Version: registry/2.0
Location: https://gcr.io/v2/xxx/flip/first/blobs/sha256:8f125ded1b483229a567e48eece98cc8867c2bee55fb73e9cd65ceecc448b7c7
Docker-Content-Digest: sha256:8f125ded1b483229a567e48eece98cc8867c2bee55fb73e9cd65ceecc448b7c7
Content-Type: application/json
Content-Encoding: gzip
Date: Fri, 27 Jul 2018 20:19:02 GMT
Server: Docker Registry
Cache-Control: private
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Alt-Svc: quic=":443"; ma=2592000; v="44,43,39,35"
Transfer-Encoding: chunked

```

### CODE REVIEW

**Comment by briandealwis** [comment]
Sorry, I forgot to actually push up the changes.  Here they are now.

**Comment by coollog** [comment]
No worries - just same comment - with skipping checking for same-registry blob mounts - for registries that don't support cross-repository blob mounts, it would probably try to resend existing blob data even if the blob exists already.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java [hunk 1]
```diff
@@ -96,7 +85,13 @@ public BlobDescriptor call() throws IOException, RegistryException, ExecutionExc
         return blobDescriptor;
       }
 
-      registryClient.pushBlob(blobDescriptor.getDigest(), blob, null);
+      // if pushing to same registry then can use `mount`/`from` to try to optimize
```
Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java]: possible rewording:

If base and target images are in the same registry, then use `mount`/`from` to try mounting the BLOb from the base image repository to the target image repository and possibly avoid having to push the BLOb. See `https://docs.docker.com/registry/spec/api/#cross-repository-blob-mount` for details.

File: jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPusher.java [hunk 2]
```diff
@@ -84,11 +85,13 @@ public URL handleResponse(Response response) throws RegistryErrorException {
 
     @Override
     public URL getApiRoute(String apiRouteBase) throws MalformedURLException {
-      return new URL(
-          apiRouteBase
-              + registryEndpointRequestProperties.getImageName()
-              + "/blobs/uploads/?mount="
-              + blobDigest);
+      String url =
```
Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPusher.java]: nit: might want to use a `StringBuilder` here.

File: jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java [hunk 3]
```diff
@@ -267,25 +267,28 @@ public Void pullBlob(DescriptorDigest blobDigest, OutputStream destinationOutput
...
       throws IOException, RegistryException {
-    BlobPusher blobPusher = new BlobPusher(registryEndpointRequestProperties, blobDigest, blob);
+    BlobPusher blobPusher =
+        new BlobPusher(registryEndpointRequestProperties, blobDigest, blob, sourceRepository);
 
     try (Timer t = parentTimer.subTimer("pushBlob")) {
       try (Timer t2 = t.subTimer("pushBlob POST " + blobDigest)) {
 
-        // POST /v2/<name>/blobs/uploads/?mount={blob.digest}
+        // POST /v2/<name>/blobs/uploads/  ?mount={blob.digest}&from={sourceRepository}
```
Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java]: Is this whitespace intentional?

Comment (briandealwis) [reply jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java]: Yeah — it's only sent if there's a mount point.  I'll clarify that.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java [hunk 4]
```diff
@@ -77,14 +77,24 @@ public BlobDescriptor call() throws IOException, RegistryException, ExecutionExc
...
 
-      registryClient.pushBlob(blobDescriptor.getDigest(), blob);
+      // If base and target images are in the same registry, then use mount/from to try mounting the
+      // BLOB from the base image repository to the target image repository and possibly avoid
+      // having to push the BLOB. See
+      // https://docs.docker.com/registry/spec/api/#cross-repository-blob-mount for details.
+      boolean sameRegistry =
+          buildConfiguration
+              .getBaseImageRegistry()
+              .equals(buildConfiguration.getTargetImageRegistry());
```
Comment (TadCordle) [inline jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java]: Btw, the presubmit is failing because I changed `BuildConfiguration` yesterday. You'll need to do something like `buildConfiguration.getTargetImageConfiguration().getImageRegistry()` now.
