### PR TITLE
Java 9 long classpath support to enable deterministic class loading order

### LINKED ISSUE #1871: Jar loading order error causes spring-boot startup to fail
**Environment**:

- *Jib version: 1.4.0*
- *Build tool: maven 3.3.9* 
- *OS: windows 10 1903*
- *Server OS [use to run Docker imange]: Linux version 5.1.14-1.el7.elrepo.x86_64 *
- Spring-boot: 2.0.6.RELEASE

**Description of the issue**:

Sorry, my English is not good, but I will try to explain the problems I have encountered.

In my project, there are two jars with different names, we call A.jar and B.jar. A rewrites and overwrites a Class with the same name in B. In order to work properly, I introduce A in pom.xml in order higher than B, which works fine in Spring-boot's Fatjar.

But when I use Jib, B always loads before A, causing the coverage of the Class to not take effect, so when the application starts, the JDK prompts "XXXX method not found in XXX.class". finally, application start failed

**Expected behavior**:

A.jar can be loaded earlier than B.jar, just like working in Spring-boot's Fatjar.

**Steps to reproduce**:

  1. add Jib maven plugin to pom.xml
  2. run command: `mvn compile jib:build -Dregistry_url={my server ip}:4000 -Dregistry_username={username} -Dregistry_password={password} -Dimage_tag=v1.2.0-dev-2019072101 -DsendCredentialsOverHttp=true`
  3. try to run docker image, spring-boot startup failed

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
</plugin>
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>jib-maven-plugin</artifactId>
    <version>1.4.0</version>
    <configuration>
        <container>
            <jvmFlags>
                <jvmFlag>-Xms512m</jvmFlag>
            </jvmFlags>
            <ports>
                <port>8080</port>
            </ports>
            <useCurrentTimestamp>true</useCurrentTimestamp>
        </container>
        <from>
            <image>registry.cn-hangzhou.aliyuncs.com/choerodon-tools/javabase:0.7.1</image>
        </from>
        <to>
            <image>${registry_url}/${docker.image.prefix}/${project.artifactId}:${maven.build.timestamp}</image>
            <auth>
                <username>${registry_username}</username>
                <password>${registry_password}</password>
            </auth>
        </to>
        <allowInsecureRegistries>true</allowInsecureRegistries>
        <jvmFlags>
            <jvmFlag>-Djava.security.edg=file:/dev/./urandom</jvmFlag>
        </jvmFlags>
        <
    </configuration>
</plugin>
```

**Log output**: 

this is maven log:

```log
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building {my-cpplication-name} 0.9.0.RELEASE
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ hcbm-iam ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Copying 2 resources
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ hcbm-iam ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- jib-maven-plugin:1.4.0:build (default-cli) @ hcbm-iam ---
[WARNING] Authentication over HTTP is enabled. It is strongly recommended that you do not enable this on a public network!
[WARNING] Setting image creation time to current time; your image may not be reproducible.
[INFO]
[INFO] Containerizing application to ?[{my server ip}:4000/contract/{my-application-name}:20190728?[0m...
[INFO] ?[1m[                              ] 0.0% complete?[0m
[INFO] ?[1m> building image to registry?[0m
[INFO] ?[1A?[1A?[1A?[0J
[INFO] ?[1A?[1mExecuting tasks:?[0m
[INFO] ?[1m[                              ] 0.0% complete?[0m
[INFO] ?[1m> pulling base image manifest?[0m
.......
[INFO] ?[1m> authenticating push to {my server ip}:4000?[0m
[INFO] ?[1m> preparing base image layer pullers?[0m
[INFO] ?[1A?[1A?[1A?[1A?[0J
[INFO] ?[1A?[1mExecuting tasks:?[0m

...// skip loading log , all success and 100%

 [INFO] ?[1A?[1mExecuting tasks:?[0m
[INFO] ?[1mExecuting tasks:?[0m
[INFO] ?[1m[==============================] 100.0% complete?[0m
[INFO] ?[1A?[1A?[0J
[INFO] ?[1m[==============================] 100.0% complete?[0m
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:21 min
[INFO] Finished at: 2019-07-29T00:31:05+08:00
[INFO] Final Memory: 50M/313M
[INFO] ------------------------------------------------------------------------

```

when application running, this is error log of spring-boot:

```log
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
2019-07-28 22:44:06.793   --- [           main]  : 
*************************** 
APPLICATION FAILED TO START 
*************************** 
 
Description: 
 
An attempt was made to call the method 

io.choerodon.mybatis.common.BaseMapper.selectOptional(Ljava/lang/Object;Lorg/hzero/mybatis/common/Criteria;)Ljava/util/List; 

but it does not exist. 

Its class, io.choerodon.mybatis.common.BaseMapper, is available from the following locations: 
 
    jar:file:/app/libs/choerodon-starter-mybatis-mapper-0.10.0.RELEASE.jar!/io/choerodon/mybatis/common/BaseMapper.class 
    jar:file:/app/libs/hzero-starter-mybatis-mapper-0.9.0.RELEASE.jar!/io/choerodon/mybatis/common/BaseMapper.class 
 
It was loaded from the following location: 
 
    file:/app/libs/choerodon-starter-mybatis-mapper-0.10.0.RELEASE.jar 
 
 
Action: 
 
Correct the classpath of your application so that it contains a single, compatible version of io.choerodon.mybatis.common.BaseMapper 
 
```

**Additional Information**: 

If you need additional information, I can always provide the party.

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #1871 (where #2733 and #1907 are duplicates).

Also addresses #2471 (AppCDS), #894, #1640, and #3147.

---

As discussed in the previous PR (https://github.com/GoogleContainerTools/jib/pull/2866#discussion_r512790086) , for Java 9+, we can always achieve explicitly listing all the dependencies by leveraging the argument file support in Java 9+, without the risk that some OS may not be able to handle an exceptionally long command. This mode will be the default for Java 9+ apps.

> But ideally, for Java 9+, I think we should really use the `@`-argument file feature; we can always preserve the classpath order while never hitting the system argument length limit. This is going to be a lot bigger change.
> 
> In sum, perhaps
> - Java 9+: always use a `@`-argument file. (`expandClasspathDependencies` is irrelevant.)
> - Java <=8: expand or not based on `expandClasspathDependencies`. Not decisive on if it should be true by default.

With this, we can always preserve the exact dependency loading order defined by the build system. Going forward, the `expandClasspathDependencies` option will have no effect with Java 9+. OTOH, Java <=8 will have to continue to set `expandClasspathDependencies` if the user wants to 

### Notable implementation details

The design has changed from the initial one.

- It creates a new layer named "jvm arg files".

- Two argument files will be created inside the layer:
   * classpath: `/app/jib-classpath-file`
   * main class: `/app/jib-main-class-file`

   Note that the main class file is not used by the implementation and thus unnecessary in this sense. (Keep reading.)

- The arg files are always created, whether it's Java 8 or 9+, or even when the user sets a custom entrypoint.

- The arg files will be very useful for people who want to get the classpath and the main class inferred by Jib at runtime. Being able to do so has been one of the most requested features that will eliminate the ugly workaround where the user had to hard-code the values that may change in newer Jib versions (e.g., by this PR). It'll be easy to read these files in an entrypoint shell script. Some notable examples:
   * [JHipster launch script](https://github.com/jhipster/generator-jhipster/blob/acd957431e74f798ec9abcc64b58fe836fd93c80/generators/server/templates/src/main/docker/jib/entrypoint.sh.ejs#L4)
   * [Stack Overflow answer with the workaround](https://stackoverflow.com/a/59361658/1701388)
   * AppCDS: #2477
   * #894
   * #3147 and [Jib extension user contribution](https://github.com/GoogleContainerTools/jib-extensions/pull/82)

### CODE REVIEW

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java [hunk 1]
```diff
@@ -636,6 +667,55 @@ static JavaContainerBuilder getJavaContainerBuilderWithBaseImage(
     return entrypoint;
   }
 
+  // It's perfectly fine to always generate a new temp file or rewrite an existing file. However,
```
Comment (mpeddada1) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java:670]: nit: perhaps we could put this in a javadoc format?

File: jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java [hunk 2]
```diff
@@ -268,22 +273,78 @@ public void testPluginConfigurationProcessor_cacheDirectorySystemProperties()
...
+        .containsExactly(
+            appCacheDirectory.resolve("jib-classpath-file"),
+            appCacheDirectory.resolve("jib-main-class-file"));
+    assertThat(layerEntries)
+        .comparingElementsUsing(EXTRACTION_PATH_OF)
+        .containsExactly("/app/jib-classpath-file", "/app/jib-main-class-file");
+  }
+
+  @Test
+  public void testWriteFileConservatively() throws IOException {
```
Comment (mpeddada1) [inline jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java:303]: we may not need this test, given `testWriteFileConservatively_updatedContent()` below?

File: jib-gradle-plugin/CHANGELOG.md [hunk 3]
```diff
@@ -9,6 +9,8 @@ All notable changes to this project will be documented in this file.
...
+- For Java 9+ apps by default, the runtime classpath explicitly lists all the dependencies, preserving the dependency loading order declared by Gradle. This is done by changing the default entrypoint to use the new classpath JVM argument file (basically `java -cp @/app/jib-classpath-file`). As such, `jib.container.expandClasspathDependencies` takes no effect for Java 9+. ([#3280](https://github.com/GoogleContainerTools/jib/pull/3280))
```
Comment (mpeddada1) [inline jib-gradle-plugin/CHANGELOG.md:13]: > As such, `jib.container.expandClasspathDependencies` takes no effect for Java 9+.
 
Let's document this in the READMEs as well.

**Review by mpeddada1 — APPROVED** [review]
Looks good! Only minor comments. We may want to update the issues listed above (or add an entry in the FAQ) with the new workaround once this feature is released.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java (hunk 1 above)
Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java:670]: In my view, this is a code comment that so relevant as a Javadoc.

**Review by chanseokoh — COMMENTED** [review]
Will merge this today.

File: jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java (hunk 2 above)
Comment (mpeddada1) [reply jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java:303]: My bad, looks good.

**Comment by chanseokoh** [comment]
Hmm.... actually I think I found an issue with this. Looking into it.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java (hunk 1 above)
Comment (mpeddada1) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java:660]: Ah I see. In that case, let's put this under `/* ...*/` for consistency.

**Comment by chanseokoh** [comment]
> Hmm.... actually I think I found an issue with this. Looking into it.

Nope, false alarm. It was that I wanted to clean up the code a bit last week.

**Review by mpeddada1 — APPROVED** [review]
Took another look. LGTM

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java (hunk 1 above)
Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: Relocated the comment (which I think is a better place actually) to prevent someone from mistakenly converting it to a Javadoc when we use the `/* ... */` style. And within a method, we've been using `//`, so I think we're good.
