### PR TITLE
Refresh bearer auth token if expired

### LINKED ISSUE #691: Jib should check and refresh access tokens as required
**Description of the issue**:
Hi, I don't know why this happens but when I specify a larger image as base image the build fails.
Both images are in the same repository. The only difference is the size, smaller is something around 50 MB and bigger 500 MB. Maybe that's just a problem with my network, but again it is hard to tell based on the error message. Actually when I look at docker.hub interface, everything looks ok, I mean that the new image was uploaded.

**Expected behavior**:
Sometimes build passes but very rarely, so that would be the expected behavior.
 
**Steps to reproduce**: 
It is hard for me to provide some steps since both images are in a private repository.

**Environment**: 
Ubuntu 18.04, jdk 1.8

**`jib-gradle-plugin` Configuration**: 
```groovy
plugins {
    id 'com.google.cloud.tools.jib' version '0.9.6'
}
apply plugin: 'java'

group 'test-jib'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

jib {
    from {
        image = 'userfeeds/base-java-image'
    }
    to {
        image = 'ghostbuster91/test-jib'
    }
    container {
        mainClass = 'Main'
    }
}
```

**Log output**: 
```
❯ ./gradlew jib --stacktrace
Starting a Gradle Daemon, 2 stopped Daemons could not be reused, use --status for details
Parallel execution with configuration on demand is an incubating feature.
warning: Base image 'userfeeds/base-java-image' does not use a specific image digest - build may not be reproducible

Containerizing application to ghostbuster91/test-jib...

Retrieving registry credentials for registry.hub.docker.com...
Getting base image userfeeds/base-java-image...
Building dependencies layer...
Building classes layer...
Building resources layer...
Retrieving registry credentials for registry.hub.docker.com...
Finalizing...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jib'.
> Build image failed, perhaps you should set a credential helper name with the configuration 'from.credHelper' or from.auth

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jib'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Build image failed, perhaps you should set a credential helper name with the configuration 'from.credHelper' or from.auth
        at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:153)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more
Caused by: com.google.cloud.tools.jib.registry.RegistryUnauthorizedException: Unauthorized for registry.hub.docker.com/ghostbuster91/test-jib
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:200)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:139)
        at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:338)
        at com.google.cloud.tools.jib.registry.RegistryClient.pushBlob(RegistryClient.java:303)
        at com.google.cloud.tools.jib.builder.steps.PushBlobStep.call(PushBlobStep.java:87)
        at com.google.cloud.tools.jib.builder.steps.PushBlobStep.call(PushBlobStep.java:35)
        at com.google.common.util.concurrent.CombinedFuture$CallableInterruptibleTask.runInterruptibly(CombinedFuture.java:181)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
Caused by: com.google.api.client.http.HttpResponseException: 401 Unauthorized
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"ghostbuster91/test-jib","Action":"pull"},{"Type":"repository","Class":"","Name":"ghostbuster91/test-jib","Action":"push"}]}]}

        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070)
        at com.google.cloud.tools.jib.http.Connection.send(Connection.java:124)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:169)
        ... 7 more


* Get more help at https://help.gradle.org

BUILD FAILED in 8m 5s
2 actionable tasks: 1 executed, 1 up-to-date

```
**Additional Information**: 
What is common for this failures is that they always took around 8-10 minutes.

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #691.

I am not particularly happy with how this is done, but there are two many complicated matters intertwined around auth, so this is it.

The basic idea is that, instead of returning a working `Authorization`, some steps in `StepsRunner` returns a working `RegistryClient`.

- `PullBaseImageStep`: returns a working `RegistryClient` (previously returned a working `Authorization`) for the base image
- `AuthenticatePushStep`: returns a working `RegistryClient` (instead of `Authorization` likewise) for the target image

`RegistryClient` is now a mutable instance. Calling `configureBasicAuth()` will make it send a basic `Authorization`, while calling `doBearerAuth()` will send a bearer token `Authorization`. So, you basically create two `RegistryClient` instances (one for base and the other for target), and then these are used throughout the build (i.e., in other `Step`s).

And if the `RegistryClient` succeeded to `doBearerAuth()`, it will auth-refresh a token if necessary.

### CODE REVIEW

**Comment by chanseokoh** [comment]
And although this was not necessary, I converted `RetrieveRegistryCredentialsStep` to a simple static helper class. I think this is simpler.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java [hunk 1]
```diff
@@ -101,73 +88,77 @@ public ImageAndAuthorization call()
...
+          "Cannot run Jib in offline mode; " + imageReference + " not found in local Jib cache");
+
+    } else if (imageReference.isTagDigest()) {
+      Optional<Image> image = getCachedBaseImage();
+      if (image.isPresent()) {
+        RegistryClient noAuthRegistryClient =
+            buildContext.newBaseImageRegistryClientFactory().newRegistryClient();
+        // TODO: passing noAuthRegistryClient may be problematic. It may return 401 unauthorized if
+        // layers have to be downloaded. https://github.com/GoogleContainerTools/jib/issues/2220
+        return new ImageAndRegistryClient(image.get(), noAuthRegistryClient);
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java]: Just restructured this part to make the issue #2220 clear.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java [hunk 2]
```diff
@@ -101,73 +88,77 @@ public ImageAndAuthorization call()
...
+                .newBaseImageRegistryClientFactory()
+                .setCredential(registryCredential)
+                .newRegistryClient();
 
         try {
-          return new ImageAndAuthorization(
-              pullBaseImage(registryAuthorization, progressEventDispatcher), registryAuthorization);
+          // TODO: refactor the code (https://github.com/GoogleContainerTools/jib/pull/2202)
+          if (registryCredential == null || registryCredential.isOAuth2RefreshToken()) {
+            throw ex;
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java]: This pattern is bad, but I just can't leave it to do the same meaningless no-auth attempt that is destined to fail. This is part of the issue #2202. This part should be restructured later. But I am not doing it here.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RegistryCredentialRetriever.java [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+import com.google.cloud.tools.jib.api.CredentialRetriever;
+import com.google.cloud.tools.jib.api.LogEvent;
+import com.google.cloud.tools.jib.configuration.BuildContext;
+import com.google.cloud.tools.jib.configuration.ImageConfiguration;
+import com.google.cloud.tools.jib.event.EventHandlers;
+import com.google.cloud.tools.jib.registry.credentials.CredentialRetrievalException;
+import java.util.Optional;
+
+/** Attempts to retrieve registry credentials. */
+class RegistryCredentialRetriever {
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RegistryCredentialRetriever.java]: Just renamed from `RetrieveRegistryCredentialsStep` (and thus simplied).

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java [hunk 4]
```diff
@@ -149,8 +147,7 @@ public StepsRunner registryPushSteps() {
     rootProgressDescription = "building image to registry";
     boolean layersRequiredLocally = buildContext.getAlwaysCacheBaseImage();
 
-    stepsToRun.add(this::retrieveTargetRegistryCredentials);
-    stepsToRun.add(this::authenticatePush);
+    stepsToRun.add(this::authenticateBearerPush);
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java]: As mentioned, two steps combined.

**Comment by chanseokoh** [comment]
Added some tests. Ready for review. PTAL

File: jib-core/src/test/java/com/google/cloud/tools/jib/registry/HttpOnlyFailoverHttpClient.java [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+
+import com.google.api.client.http.GenericUrl;
+import com.google.cloud.tools.jib.http.FailoverHttpClient;
+import com.google.cloud.tools.jib.http.Request;
+import com.google.cloud.tools.jib.http.Response;
+import java.io.IOException;
+import java.net.URL;
+
+/** Forces sending all requests in plain-HTTP protocol. For testing only. */
+class HttpOnlyFailoverHttpClient extends FailoverHttpClient {
```
Comment (briandealwis) [inline jib-core/src/test/java/com/google/cloud/tools/jib/registry/HttpOnlyFailoverHttpClient.java]: `PlainHttpClient`?

File: jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java [hunk 6]
```diff
@@ -242,46 +252,113 @@ public static Factory factory(
...
+    eventHandlers.dispatch(
+        LogEvent.debug("configured basic auth for " + registry + "/" + repository));
+  }
+
   /**
-   * @return the {@link RegistryAuthenticator} to authenticate pulls/pushes with the registry, or
-   *     {@link Optional#empty()} if no token authentication is necessary
+   * Attempts bearer authentication.
+   *
+   * @param readOnlyBearerAuth true to request pull scope only; false for pull and push
```
Comment (loosebazooka) [inline jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java]: should readOnly be a fixed value of a registry client? Do we intend to reuse a registry client to do readonly once and then write later?
Perhaps this can go on the factory?

Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java]: As the name suggested, this read-only vs. read-write applies only when doing bearer auth. Before doing any auth or in the case of basic auth, the registry client itself is unrestricted. It will then be the server who will say you cannot do anything, can read, or can read and write.

The class is mutable, and potentially it's possible to do `doBearerAuth(true)` and later `doBearerAuth(false)`, but I never intend to do it. But the point is, the client doesn't know if it's going to be read only (actually just requesting read only) before doing `doBearerAuth()`. And it is a bit sad, but I don't think the factory should initiate `doBearerAuth()`.

File: jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java [hunk 7]
```diff
@@ -242,46 +252,113 @@ public static Factory factory(
...
    */
-  public Optional<RegistryAuthenticator> getRegistryAuthenticator()
-      throws IOException, RegistryException {
-    // Gets the WWW-Authenticate header (eg. 'WWW-Authenticate: Bearer
-    // realm="https://gcr.io/v2/token",service="gcr.io"')
-    return callRegistryEndpoint(
-        new AuthenticationMethodRetriever(
-            registryEndpointRequestProperties, getUserAgent(), httpClient));
+  public boolean doBearerAuth(boolean readOnlyBearerAuth) throws IOException, RegistryException {
+    this.readOnlyBearerAuth = readOnlyBearerAuth;
```
[the remark this answers is not in the document]
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java]: Technically you can still use it to make these requests (theoretically it works as long as the server doesn't reject), but I've added a check anyway.

File: jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java [hunk 8]
```diff
@@ -463,13 +544,31 @@ String getUserAgent() {
...
+                authorization.get(),
+                registryEndpointRequestProperties,
+                httpClient)
+            .call();
+
+      } catch (RegistryUnauthorizedException ex) {
+        if (ex.getHttpResponseException().getStatusCode()
+                != HttpStatusCodes.STATUS_CODE_UNAUTHORIZED
+            || !isBearerAuth(authorization.get())
+            || ++bearerTokenRefreshes >= 5) {
```
[the remark this answers is not in the document]
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java]: I think a const here.

**Comment by chanseokoh** [comment]
Forgot to answer: unfortunately, the only way I find to refresh auth tokens to fix #691 is to make `RegistryClient` do it (i.e., doing the auth). It is sad that this class has to become mutable, but since some operation is a transaction composed of muliple registry interactions, so the refresh cannot be done outside the client. And to initiate the auth,  you first need a working registry client: the chicken-and-egg problem.

The client was never used concurrently. We created a fresh new instance whenever we wanted to talk to a registry. This is going to change and we will create only two instances for base and target. Therefore it has to be thread-safe.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java (hunk 2 above)
Comment (loosebazooka) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java]: is the restructure required before we do a 2.0.0?

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java [hunk 9]
```diff
@@ -101,73 +88,81 @@ public ImageAndAuthorization call()
...
+              LogEvent.debug("Trying bearer auth for " + imageReference + "..."));
+          if (registryClient.doBearerAuth(true)) {
+            return new ImageAndRegistryClient(
+                pullBaseImage(registryClient, progressEventDispatcher), registryClient);
           }
           eventHandlers.dispatch(
               LogEvent.error(
-                  "Failed to retrieve authentication challenge for registry that required token "
-                      + "authentication"));
+                  "The registry asked for basic authentication, but the registry had refused basic"
```
[the remark this answers is not in the document]
Comment (loosebazooka) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java]: probably don't need `had` either.
```diff
- the registry had refused
+ the registry refused
```

[the remark this answers is not in the document]
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java]: I think "had" is fine? It makes it explicit that the refusal had happened before the server asked for basic auth.

File: jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java [hunk 10]
```diff
@@ -242,46 +254,112 @@ public static Factory factory(
...
+   *     sent over plain HTTP
    */
-  public Optional<RegistryAuthenticator> getRegistryAuthenticator()
-      throws IOException, RegistryException {
-    // Gets the WWW-Authenticate header (eg. 'WWW-Authenticate: Bearer
-    // realm="https://gcr.io/v2/token",service="gcr.io"')
-    return callRegistryEndpoint(
-        new AuthenticationMethodRetriever(
-            registryEndpointRequestProperties, getUserAgent(), httpClient));
+  public boolean doBearerAuth(boolean readOnlyBearerAuth) throws IOException, RegistryException {
```
[the remark this answers is not in the document]
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java]: Ah, didn't know that. I can do it that way.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java (hunk 2 above)
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java]: It's not required. But as of now (which doesn't have this jump), you just make the same meaningless call with null credential only to fail again. (In line 126, we already failed with "noAuthRegistryClient". No reason to do this again.) This is a simple guard, so I think this is safe. I want to have this in 2.0.0 for better performance. Most registries will hit this path.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java [hunk 11]
```diff
@@ -21,58 +21,53 @@
...
     this.progressEventDispatcherFactory = progressEventDispatcherFactory;
-    this.registryCredential = registryCredential;
   }
 
   @Override
-  public Optional<Authorization> call() throws IOException, RegistryException {
+  public RegistryClient call() throws CredentialRetrievalException, IOException, RegistryException {
     String registry = buildContext.getTargetImageConfiguration().getImageRegistry();
     try (ProgressEventDispatcher ignored =
             progressEventDispatcherFactory.create("authenticating push to " + registry, 1);
```
Comment (loosebazooka) [inline jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java]: Does it make sense to make this 2 allocation units now, or is it so quick, this doesn't really matter.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java [hunk 12]
```diff
@@ -21,58 +21,53 @@
...
+          RegistryCredentialRetriever.getTargetImageCredential(buildContext).orElse(null);
+
+      RegistryClient registryClient =
           buildContext
               .newTargetImageRegistryClientFactory()
-              .newRegistryClient()
-              .getRegistryAuthenticator();
-      if (registryAuthenticator.isPresent()) {
-        return Optional.of(registryAuthenticator.get().authenticatePush(registryCredential));
+              .setCredential(credential)
```
Comment (loosebazooka) [inline jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java]: I find this flow to be a little strange. But maybe that's just a consequence of our code, should the registry client just handle this basic auth stuff? 

Is there a reason we want the steps of authorizing the client to exist separate and outside the client?

Comment (loosebazooka) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java]: Actually looking at stuff further down the code, the flow is ever so slightly different everywhere?

Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java]: Yeah. I understand the flow may seem strange and make you think perhaps logic could just be put inside the registry client. I thought the same.

I don't have any history, but our way of doing auth has been like this:

- For pull (base image): first try without any credentials. If it fails, configure basic auth no matter what and try again. If it fails, initiate pull bearer auth.
- For push (target image): always initiate push bearer auth first. If the server returns asking for basic auth, configure basic auth.

So, for now, basically the overall auth logic is different per use-case and needs to be defined at a higher-level per. That's why I made the registry client provides the necessary knobs (`configureBasicAuth` and `doPull/PushBearerAuth`) and let the caller decided how to drive it.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java (hunk 11 above)
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java]: I find no problem to have 2 allocations.
