### PR TITLE
Fix FileOperationsTest: tryLock() can return null

### LINKED ISSUE #1267: Flaky test failure on FileOperations.newLockingOutputStream
Got an interesting flaky test failure.

```
com.google.cloud.tools.jib.filesystem.FileOperationsTest > testNewLockingOutputStream_newFile FAILED
    java.lang.AssertionError: Lock attempt should have failed
        at org.junit.Assert.fail(Assert.java:88)
        at com.google.cloud.tools.jib.filesystem.FileOperationsTest.verifyWriteWithLock(FileOperationsTest.java:49)
        at com.google.cloud.tools.jib.filesystem.FileOperationsTest.testNewLockingOutputStream_newFile(FileOperationsTest.java:98)
```

Full log: https://source.cloud.google.com/results/invocations/c9d1aec1-105e-4225-89e4-129a3c80390a/log

Test code:
```java
  private static void verifyWriteWithLock(Path file) throws IOException {
    OutputStream fileOutputStream = FileOperations.newLockingOutputStream(file);

    // Checks that the file was locked.
    try {
      FileChannel.open(file, StandardOpenOption.READ).tryLock(0, Long.MAX_VALUE, true);
      Assert.fail("Lock attempt should have failed");

    } catch (OverlappingFileLockException ex) {
      // pass
    }
```

### PR DESCRIPTION
**Pull request by briandealwis**
Fix #1267

### CODE REVIEW

File: jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/FileOperationsTest.java [hunk 1]
```diff
@@ -44,9 +45,10 @@ private static void verifyWriteWithLock(Path file) throws IOException {
     OutputStream fileOutputStream = FileOperations.newLockingOutputStream(file);
 
     // Checks that the file was locked.
-    try {
-      FileChannel.open(file, StandardOpenOption.READ).tryLock(0, Long.MAX_VALUE, true);
-      Assert.fail("Lock attempt should have failed");
+    try (FileChannel channel = FileChannel.open(file, StandardOpenOption.READ)) {
+      // locking should either fail and return null or throw an OverlappingFileLockException
+      FileLock lock = channel.tryLock(0, Long.MAX_VALUE, true);
```
Comment (chanseokoh) [inline jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/FileOperationsTest.java]: What if we do `lock()` instead of `tryLock()`?

Comment (briandealwis) [reply jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/FileOperationsTest.java]: It would result in a deadlock.  This `tryLock()` should fail since the stream returned by `FileOperations.newLockingOutputStream()` should be locked.
