### PR TITLE
Avoid creating directory in exploded-war build output directory in Ja…

### LINKED ISSUE #1164: To fix: JavaLayerConfigurationsHelperTest
**Description of the issue**: Test failure

**Expected behavior**: Test success

**Steps to reproduce**: 

```shell
cd jib-maven-plugin
./mvnw verify -Pintegration-tests
```

**Environment**: 

Linux rodete

**Log output**: 

```
[INFO] Running com.google.cloud.tools.jib.plugins.common.JavaLayerConfigurationsHelperTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in com.google.cloud.tools.jib.plugins.common.JavaLayerConfigurationsHelperTest
[ERROR] testFromExplodedWar(com.google.cloud.tools.jib.plugins.common.JavaLayerConfigurationsHelperTest)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError: expected:<[/usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/META-INF, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/META-INF/context.xml, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/Test.jsp, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes/empty_dir, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes/package, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes/package/test.properties, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/lib, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/web.xml]> but was:<[/usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/META-INF, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/META-INF/context.xml, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/Test.jsp, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes/empty_dir, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes/package, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes/package/test.properties, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/lib, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/web.xml, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/file]>
	at com.google.cloud.tools.jib.plugins.common.JavaLayerConfigurationsHelperTest.assertLayerEntriesUnordered(JavaLayerConfigurationsHelperTest.java:42)
	at com.google.cloud.tools.jib.plugins.common.JavaLayerConfigurationsHelperTest.assertSourcePathsUnordered(JavaLayerConfigurationsHelperTest.java:47)
	at com.google.cloud.tools.jib.plugins.common.JavaLayerConfigurationsHelperTest.testFromExplodedWar(JavaLayerConfigurationsHelperTest.java:72)
```

### PR DESCRIPTION
**Pull request by TadCordle**
Closes #1164. Copies test resources to a temp directory we can operate on instead of polluting the test files.

### CODE REVIEW

**Comment by TadCordle** [comment]
This was less to fix the original issue and more to address https://github.com/GoogleContainerTools/jib/issues/1164#issuecomment-431375516 from a cleanliness standpoint; I probably wasn't clear enough about that.

File: jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelperTest.java [hunk 1]
```diff
@@ -25,17 +25,23 @@
...
+import java.util.stream.Stream;
 import org.junit.Assert;
+import org.junit.ClassRule;
 import org.junit.Test;
+import org.junit.rules.TemporaryFolder;
 
 /** Tests for {@link JavaLayerConfigurationsHelper}. */
 public class JavaLayerConfigurationsHelperTest {
 
+  @ClassRule public static TemporaryFolder temporaryFolder = new TemporaryFolder();
```
Comment (coollog) [inline jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelperTest.java]: Since this is only one test, this would work, but if we were to add more tests this `TemporaryFolder` would be shared between the tests. This is okay if we have our convention be that we would never use the `TemporaryFolder` root for a test and always call `newFolder`, but in other parts of the codebase we have `TemporaryFolder` be non-static and we do use the root sometimes. Doesn't have to be in this PR, but I think we should just set some convention here and make sure we are consistent across all our uses of `TemporaryFolder`.

File: jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelperTest.java [hunk 2]
```diff
@@ -56,43 +62,59 @@ private static void assertExtractionPathsUnordered(
 
   @Test
   public void testFromExplodedWar() throws URISyntaxException, IOException {
-    Path explodedWar = Paths.get(Resources.getResource("exploded-war").toURI());
-    Files.createDirectories(explodedWar.resolve("WEB-INF/classes/empty_dir"));
+    // Copy test files to a temporary directory that we can safely operate on
+    Path temporaryExplodedWar = temporaryFolder.newFolder("exploded-war").toPath();
+    Path resourceExplodedWar = Paths.get(Resources.getResource("exploded-war").toURI());
+    try (Stream<Path> stream = Files.walk(resourceExplodedWar)) {
```
Comment (coollog) [inline jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelperTest.java]: We have `FileOperations#copy` that does the recursive copy - I believe we can use that here. There're also some other tests that do this kind of copy directory setup and we might want to use the `FileOperations#copy` method too so we don't have duplicate recursive copy implementations in various places.
