### PR TITLE
Try Google Application Default Credentials for GCR (gcr.io) auth

### LINKED ISSUE #1500: Maven jib:dockerBuild in Google Cloud Build fails
**Description of the issue**:
Attempting to build and deploy a container from within Google Cloud Build.
`jib:build` wants me to authenticate within the same project where GCB and GCR run. It feels wrong to attempt to add this so I am attempting to use `jib:dockerBuild`.
 
```yaml
  - name: 'gcr.io/cloud-builders/mvn'
    id: MVN_COMPILE
    args: ['compile','jib:dockerBuild', '-Dmaven.test.skip=true', '-Ddocker.image.prefix=gcr.io/$PROJECT_ID', '-s', '.mvn/settings.xml']

images:
  - 'gcr.io/$PROJECT_ID/my-company-project'

```
But I am getting an error that Google Cloud Build does not have a docker daemon running. I can run both the `jib:build` and `jib:dockerBuild` locally, but need the CI to work as a trigger in Google Cloud Builder.

**Steps to reproduce**: 
Simply using Google cloud build via triggers or `gcloud builds submit .`

**Environment**: 

**`jib-maven-plugin` Configuration**: 
```xml
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>1.0.0</version>
            </plugin>
```

**Log output**: 
```
Step #3 - "MVN_COMPILE": [ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.0.0:dockerBuild (default-cli) on project my-company-project: Build to Docker daemon failed, perhaps you should make sure Docker is installed and you have correct privileges to run it -> [Help 1]
```

### LINKED ISSUE #1903: Jib: seamless and automatic GCR (gcr.io) auth on GCP using Application Default Credentials (ADC): Google Cloud Build (GCB), Google Compute Engine (GCE), Google Kubernetes Engine (GKE), Cloud SDK application-default, service accounts, GOOGLE_APPLICATION_CREDENTIALS, etc
Creating an issue for easy lookup and search as well as for future reference.

On GCP, if no credentials were configured or could be retrieved for GCR access, Jib should try ADC that are available on most GCP environments as a last attempt. This will effectively resolve the case like #1500.

ADC from Cloud SDK
---
Jib can get ADC set through `gcloud auth application-default login`. ADC in this case are "end user credentials".

```
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
[DEBUG] Google ADC found
[DEBUG] Using Google Application Default Credentials for gcr.io
...
[INFO] Built and pushed image as gcr.io/<redacted>/test
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

ADC from Service Account
---
The current implementation for a service account is to generate a short-lived OAuth2 access token from the service account and use it for GCR auth.

```
$ GOOGLE_APPLICATION_CREDENTIALS=my-service-account-key.json mvn -X jib:build
...
[DEBUG] Google ADC found
[DEBUG] ADC is a service account. Set GCS read-write scope
[DEBUG] Using Google Application Default Credentials for gcr.io
...
[INFO] Built and pushed image as gcr.io/<redacted>/test
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

ADC on Google Cloud Build (GCB)
---
ADC are available on GCB and have the permission to push to GCR.
```
[DEBUG] Google ADC found
[DEBUG] Using Google Application Default Credentials for gcr.io
...
[INFO] Built and pushed image as gcr.io/<redacted>/gcb-test
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
...
PUSH
DONE
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ID                                    CREATE_TIME                DURATION  SOURCE                                                                                             IMAGES  STATUS
0b9e0bb2-3cdb-4e7d-8954-86d5ba0b7e72  2019-08-12T21:08:27+00:00  1M55S     gs://<redacted>_cloudbuild/source/1565644104.23-97f5c662bd70409186821171c3a06db0.tgz  -       SUCCESS
```

ADC on Google Compute Engine (GCE)
---
Tested on Linux and Windows:
```
[DEBUG] Google ADC found
[DEBUG] Using Google Application Default Credentials for gcr.io
...
[INFO] Built and pushed image as gcr.io/<redacted>/adc-gce
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

ADC on Google Kubernetes Engine (GKE)
---

ADC on Cloud Shell
---
Confirmed it works. However, Cloud Shell has `docker-credential-gcloud`, `docker-credential-gcr`, and `~/.docker/config.json`, so it's already working pretty well without this ADC support.
```
[DEBUG] Google ADC found
[DEBUG] Using Google Application Default Credentials for gcr.io
```

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #1903.

Closes #1500.

ADC from Cloud SDK
---
Jib can get ADC set through `gcloud auth application-default login`. ADC in this case are "end user credentials".

```
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
[DEBUG] Google ADC found
[DEBUG] Using Google Application Default Credentials for gcr.io
...
[INFO] Built and pushed image as gcr.io/<redacted>/test
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

ADC from Service Account
---
The current implementation for a service account is to generate a short-lived OAuth2 access token from the service account and use it for GCR auth.

```
$ GOOGLE_APPLICATION_CREDENTIALS=my-service-account-key.json mvn -X jib:build
...
[DEBUG] Google ADC found
[DEBUG] ADC is a service account. Set GCS read-write scope
[DEBUG] Using Google Application Default Credentials for gcr.io
...
[INFO] Built and pushed image as gcr.io/<redacted>/test
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

ADC on Google Cloud Build (GCB)
---
ADC are available on GCB and have the permission to push to GCR.
```
[DEBUG] Google ADC found
[DEBUG] Using Google Application Default Credentials for gcr.io
...
[INFO] Built and pushed image as gcr.io/<redacted>/gcb-test
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
...
PUSH
DONE
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ID                                    CREATE_TIME                DURATION  SOURCE                                                                                             IMAGES  STATUS
0b9e0bb2-3cdb-4e7d-8954-86d5ba0b7e72  2019-08-12T21:08:27+00:00  1M55S     gs://<redacted>_cloudbuild/source/1565644104.23-97f5c662bd70409186821171c3a06db0.tgz  -       SUCCESS
```

ADC on Google Compute Engine (GCE)
---
Tested on Linux and Windows:
```
[DEBUG] Google ADC found
[DEBUG] Using Google Application Default Credentials for gcr.io
...
[INFO] Built and pushed image as gcr.io/<redacted>/adc-gce
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

ADC on Google Kubernetes Engine (GKE)
---

ADC on Cloud Shell
---
Confirmed it works. However, Cloud Shell has `docker-credential-gcloud`, `docker-credential-gcr`, and `~/.docker/config.json`, so it's already working pretty well without this ADC support.
```
[DEBUG] Google ADC found
[DEBUG] Using Google Application Default Credentials for gcr.io
```

### CODE REVIEW

**Comment by chanseokoh** [comment]
Out of the draft status. Ready for review.

File: jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java [hunk 1]
```diff
@@ -143,33 +150,25 @@ public CredentialRetriever dockerCredentialHelper(Path credentialHelper) {
...
-      if (!imageReference.getRegistry().endsWith(registrySuffix)) {
-        continue;
-      }
-      String inferredCredentialHelperSuffix = COMMON_CREDENTIAL_HELPERS.get(registrySuffix);
-      if (inferredCredentialHelperSuffix == null) {
-        throw new IllegalStateException("No COMMON_CREDENTIAL_HELPERS should be null");
-      }
-      inferredCredentialHelperSuffixes.add(inferredCredentialHelperSuffix);
-    }
+  public CredentialRetriever wellKnownCredentialHelper() {
```
Comment (briandealwis) [inline jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java]: Should this be plural? (`Helper*s*`)

File: jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java [hunk 2]
```diff
@@ -143,33 +150,25 @@ public CredentialRetriever dockerCredentialHelper(Path credentialHelper) {
...
+    List<String> wellKnownCredentialHelpers =
+        WELL_KNOWN_CREDENTIAL_HELPERS
+            .keySet()
+            .stream()
+            .filter(imageReference.getRegistry()::endsWith)
+            .map(key -> Verify.verifyNotNull(WELL_KNOWN_CREDENTIAL_HELPERS.get(key)))
```
Comment (briandealwis) [inline jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java]: This code isn't necessary as Guava's [immutable collections are "null hostile"](https://github.com/google/guava/wiki/LivingWithNullHostileCollections).

File: jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java [hunk 3]
```diff
@@ -213,18 +212,55 @@ public CredentialRetriever dockerConfig(Path dockerConfigFile) {
...
+          if (googleCredentials.createScopedRequired()) { // Not scoped if service account.
+            // The short-lived OAuth2 access token generated from the service account will have
+            // one-hour expiry (as of Aug 2019). Instead of using an access token, It is technically
+            // possible to use the service account private key to auth with GCR, but it does not
+            // worth writing complex code to achieve that.
+            logger.accept(LogEvent.info("ADC is a service account. Set GCS read-write scope"));
+            List<String> scope = Collections.singletonList(OAUTH_SCOPE_STORAGE_READ_WRITE);
+            googleCredentials = googleCredentials.createScoped(scope);
+          }
+          googleCredentials.refresh();
```
Comment (briandealwis) [inline jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java]: Would it make sense to use `refreshIfExpired()`?  It checks if the access token expiry is soonish (looks like 5 minutes).

File: jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java [hunk 4]
```diff
@@ -65,7 +63,7 @@ public DockerCredentialHelper(String serverUrl, Path credentialHelper) {
   }
 
   DockerCredentialHelper(String registry, String credentialHelperSuffix) {
-    this(registry, Paths.get(CREDENTIAL_HELPER_PREFIX + credentialHelperSuffix));
+    this(registry, Paths.get("docker-credential-" + credentialHelperSuffix));
```
Comment (briandealwis) [inline jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java]: I wonder if we should get rid of this method and push knowledge of the `docker-credential-` prefix to the callers/creators?

File: jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java [hunk 5]
```diff
@@ -61,32 +74,28 @@
...
+        imageReference,
+        logger,
+        DockerCredentialHelper::new,
+        GoogleCredentials::getApplicationDefault);
   }
 
   private final ImageReference imageReference;
   private final Consumer<LogEvent> logger;
   private final DockerCredentialHelperFactory dockerCredentialHelperFactory;
+  private final GoogleCredentialsProvider googleCredentialsProvider;
```
Comment (briandealwis) [inline jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java]: Could this not be a `Supplier<GoogleCredentials>`?

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java [hunk 6]
```diff
@@ -121,24 +123,24 @@ public DefaultCredentialRetrievers setCredentialHelper(@Nullable String credenti
...
+            credentialRetrieverFactory.dockerCredentialHelper("docker-credential-" + suffix));
       }
     }
     if (inferredCredentialRetriever != null) {
       credentialRetrievers.add(inferredCredentialRetriever);
     }
     credentialRetrievers.add(credentialRetrieverFactory.dockerConfig());
-    credentialRetrievers.add(credentialRetrieverFactory.inferCredentialHelper());
+    credentialRetrievers.add(credentialRetrieverFactory.wellKnownCredentialHelper());
+    credentialRetrievers.add(credentialRetrieverFactory.googleApplicationDefaultCredentials());
```
Comment (briandealwis) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java]: Shouldn't `googleApplicationDefaultCredentials()` come before `wellKnownCredentialHelper()`?

File: jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java (hunk 4 above)
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java]: Let me take care of this in a separate PR.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java (hunk 6 above)
Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java]: I think ADC should be tried as a last resort. For example, the default GCE service account has a project editor role by default, but you can create instances with different roles. So most of the time, Jib will work out of the box, but ADC doesn't guarantee pushing to GCR will succeed.

File: jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java [hunk 7]
```diff
@@ -143,33 +149,25 @@ public CredentialRetriever dockerCredentialHelper(Path credentialHelper) {
...
-      if (!imageReference.getRegistry().endsWith(registrySuffix)) {
-        continue;
-      }
-      String inferredCredentialHelperSuffix = COMMON_CREDENTIAL_HELPERS.get(registrySuffix);
-      if (inferredCredentialHelperSuffix == null) {
-        throw new IllegalStateException("No COMMON_CREDENTIAL_HELPERS should be null");
-      }
-      inferredCredentialHelperSuffixes.add(inferredCredentialHelperSuffix);
-    }
+  public CredentialRetriever wellKnownCredentialHelpers() {
```
Comment (briandealwis) [inline jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java]: Sorry, I retract my previous comment :-(. This should be singular, since we return a single element.  Maybe `findWellKnownCredentialHelper()`?

File: jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java [hunk 8]
```diff
@@ -143,33 +149,25 @@ public CredentialRetriever dockerCredentialHelper(Path credentialHelper) {
...
+    List<String> wellKnownCredentialHelpers =
+        WELL_KNOWN_CREDENTIAL_HELPERS
+            .keySet()
+            .stream()
+            .filter(imageReference.getRegistry()::endsWith)
+            .map(key -> WELL_KNOWN_CREDENTIAL_HELPERS.get(key))
+            .collect(Collectors.toList());
```
Comment (briandealwis) [inline jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java]: IMHO it is simpler to just iterate over `WELL_KNOWN_CREDENTIAL_HELPERS.entrySet()` inside the lambda below.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java (hunk 6 above)
Comment (briandealwis) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java]: Makes sense.

File: jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java [hunk 9]
```diff
@@ -39,82 +39,88 @@
...
-  @Mock private CredentialRetriever mockInferredCredentialRetriever;
-  @Mock private CredentialRetriever mockInferCredentialHelperCredentialRetriever;
-  @Mock private CredentialRetriever mockDockerConfigCredentialRetriever;
+  @Mock private CredentialRetrieverFactory credentialRetrieverFactory;
+  @Mock private CredentialRetriever dockerCredentialHelperCredentialRetriever;
+  @Mock private CredentialRetriever knownCredentialRetriever;
+  @Mock private CredentialRetriever inferredCredentialRetriever;
+  @Mock private CredentialRetriever inferCredentialHelperCredentialRetriever;
+  @Mock private CredentialRetriever dockerConfigCredentialRetriever;
+  @Mock private CredentialRetriever applicationDefaultCredentialRetriever;
```
Comment (briandealwis) [inline jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java]: It would be better to leave these type of renames to separate PRs.  There was a preference to explicitly indicate mocked objects with a `mock` prefix, though it's not documented in the `STYLE_GUIDE.md`

File: jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java (hunk 7 above)
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java]: I actually think the plural makes sense. It is not returning cred helper(s) but rather a retriever, which may attempt more than one cred helper. For example, the mock instance in the test for this is called `mockWellKnownCredentialHelpersCredentialRetriever`.

And using a verb makes sense, but because all the methods of this class don't use verb (`dockerConfig()`, `known()`, `dockerCredentialHelper()`, and `googleApplicationDefaultCredentials()`), I will retain without-verb names. Maybe a separate PR.

File: jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java (hunk 8 above)
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java]: Oh, yeah, that's so true.

File: jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java (hunk 7 above)
Comment (briandealwis) [reply jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java]: ok

File: jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java [hunk 10]
```diff
@@ -44,118 +47,189 @@
...
-  @Mock private DockerConfigCredentialRetriever mockDockerConfigCredentialRetriever;
-
-  /** A {@link DockerCredentialHelper} that throws {@link CredentialHelperNotFoundException}. */
-  @Mock private DockerCredentialHelper mockNonexistentDockerCredentialHelper;
-
-  @Mock private CredentialHelperNotFoundException mockCredentialHelperNotFoundException;
+  @Mock private Consumer<LogEvent> logger;
+  @Mock private DockerCredentialHelper dockerCredentialHelper;
+  @Mock private DockerCredentialHelperFactory dockerCredentialHelperFactory;
+  @Mock private GoogleCredentials googleCredentials;
```
Comment (briandealwis) [inline jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java]: Possible to back these `mock` prefix changes out too?

Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java]: Oops, missed this class.

File: jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java [hunk 11]
```diff
@@ -227,10 +227,10 @@ public CredentialRetriever googleApplicationDefaultCredentials() {
...
           if (googleCredentials.createScopedRequired()) { // not scoped if service account
-            // The short-lived OAuth2 access token generated from the service account will have
-            // one-hour expiry (as of Aug 2019). Instead of using an access token, it is technically
-            // possible to use the service account private key to auth with GCR, but it does not
-            // worth writing complex code to achieve that.
+            // The short-lived OAuth2 access token to be generated from the service account with
+            // refreshIfExpired() below will have one-hour expiry (as of Aug 2019). Instead of using
+            // an access token, it is technically possible to use the service account private key to
+            // auth with GCR, but it does not worth writing complex code to achieve that.
             logger.accept(LogEvent.info("ADC is a service account. Set GCS read-write scope"));
```
Comment (briandealwis) [inline jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java]: `Setting GCS…`?
