### PR TITLE
Make Error Prone happy

### LINKED ISSUE #705: Fix warnings when building gradle plugin
`$ ./gradlew clean goJF build` causes two types of warnings at the moment.

- [x] Unchecked future result
```
> Task :compileTestJava 
(...)/jib/jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java:40: warning: [FutureReturnValueIgnored] Return value of methods returning Future must be checked. Ignoring returned Futures suppresses exceptions thrown from the code that completes the Future.
    executorService.submit(this::serve200);
                          ^
    (see http://errorprone.info/bugpattern/FutureReturnValueIgnored)
  Did you mean to remove this line?
1 warning
```

- [x] `@Input` annotation used on `java.io.File`
```
> Task :validateTaskProperties 
Task property validation finished with warnings:
  - Warning: Task type 'com.google.cloud.tools.jib.gradle.BuildDockerTask': property 'jib.extraDirectory' has @Input annotation used on property of type java.io.File.
  - Warning: Task type 'com.google.cloud.tools.jib.gradle.BuildImageTask': property 'jib.extraDirectory' has @Input annotation used on property of type java.io.File.
  - Warning: Task type 'com.google.cloud.tools.jib.gradle.BuildTarTask': property 'jib.extraDirectory' has @Input annotation used on property of type java.io.File.
  - Warning: Task type 'com.google.cloud.tools.jib.gradle.DockerContextTask': property 'jib.extraDirectory' has @Input annotation used on property of type java.io.File.
```

### PR DESCRIPTION
**Pull request by chanseokoh**
Part of #705.

### CODE REVIEW

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java [hunk 1]
```diff
@@ -35,7 +36,7 @@
 
   TestWebServer() throws IOException, InterruptedException {
     serverSocket = new ServerSocket(0);
-    executorService.submit(this::serve200);
+    ignoreReturn(executorService.submit(this::serve200));
```
Comment (coollog) [inline jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: I'm kinda late here again but the [`@CanIgnoreReturnValue`](https://errorprone.info/api/latest/com/google/errorprone/annotations/CanIgnoreReturnValue.html) annotation can be an alternative:

```java
@CanIgnoreReturnValue
private static Future<Void> runOnExecutorService(Callable<Void> callable) {
  return executorService.submit(callable);
}
```
