### PR TITLE
Replace assemble task dependency with runtimeClasspath

### LINKED ISSUE #2184: Too many tasks executed on jib build
**Description of the issue**:
While using the jib gradle task (jib) the Plugin configures the jib tasks to depend on ALL assemble tasks on all upstream projects in a multi project build. This causes lots of unecessary artifacts being build even if only the jar (default dependency) of any upstream project is used.

**Expected behavior**:
If the plugin is applied only the default dependency should be used, which in fact is already evaluated for the build of the project (jar/classes). So there should be no need at all to depend on anything on the parent projects. If specific artifacts are needed by a specific project the project should configure this dependency itself, it should not be hard coded within the Jib Plugin itself.

**Steps to reproduce**:

Its in the original code:
`
 COPIED FROM JibPlugin.java:

            // Find project dependencies and add a dependency to their assemble task. We make sure
            // to only add the dependency after BasePlugin is evaluated as otherwise the assemble
            // task may not be available yet.
            List<Project> computedDependencies = getProjectDependencies(projectAfterEvaluation);
            for (Project dependencyProject : computedDependencies) {
              dependencyProject
                  .getPlugins()
                  .withType(
                      BasePlugin.class,
                      unused -> {
                        TaskProvider<Task> assembleTask =
                            dependencyProject.getTasks().named(BasePlugin.ASSEMBLE_TASK_NAME);
                        buildImageTask.configure(task -> task.dependsOn(assembleTask));
                        buildDockerTask.configure(task -> task.dependsOn(assembleTask));
                        buildTarTask.configure(task -> task.dependsOn(assembleTask));
                      });
            }
`
If some kind of dependency  is really required, there should be a minimal dependency setup from any required project. Normally this should only be the "default" gradle artifact - including the classpath.

### PR DESCRIPTION
**Pull request by seanabraham**
This introduces a new lifecycle task called `jibDependencies` (the name can really be anything, that was just what I came up with) that all the jib tasks depend on and it in turn depends on any requisite tasks / configurations. Being a lifecycle task, it doesn't have any task action itself and essentially exists as a convenient hook for other dependencies. In particular, `jibDependencies` will depend on the `war`/`bootWar` tasks  when applicable, the `jar` task when applicable, and always depends on the projects `runtimeClasspath` configuration.

Gradle allows tasks to depend on `FileCollection`s (rather than just tasks). When doing so Gradle expands the task graph expands to include all the necessary tasks to produce the files listed in the `FileCollection`. Doing so with the `runtimeClasspath` configuration means Gradle will run all the tasks to get all the artifacts necessary to run this project, making it more efficient than using the `assemble` task which will often run slow, and unnecessary tasks. In particular, the main source set's `runtimeClasspath`'s property includes the source set output appended to the project's `runtimeClasspath` configuration so depending on that obviates the need to run even manually run the `classes` task. (See https://docs.gradle.org/current/userguide/java_plugin.html#sec:source_set_properties)

 If we only want to conditionally depend on the runtime classpath I'm happy to make that change though I assume it's never really going to be a bad thing even in the case of the `war` based projects.

Also, for what it's worth — jib itself uses the `runtimeClasspath` to get the list of files to add to the container so it makes sense to use that same collection to set up the task dependencies.
https://github.com/GoogleContainerTools/jib/blob/d3615a6df6f0f7e2654466128e685ea7ee73958a/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java#L174 

There are a few different potential approaches here so I'm happy to make changes to go with a different approach. For example, we don't _have_ to introduce the `jibDependencies` task but it made the implementation a little cleaner and also made it so that the changes to tests were minimal (some of them make assumptions about the contents of `task.getDependsOn()` which are no longer true when tasks depend on configurations for example). It might also be useful in the future if there are new dependencies since they can all hook into `jibDependencies`.

This should resolve #2184

### CODE REVIEW

**Comment by seanabraham** [comment]
@googlebot I signed it!

File: jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java [hunk 1]
```diff
@@ -212,11 +143,19 @@ public void testWebAppProject() {
...
+    Assert.assertTrue(taskDependencies.contains(warTask));
+
     for (String taskName : KNOWN_JIB_TASKS) {
-      List<TaskProvider<?>> taskProviders =
-          (List<TaskProvider<?>>) tasks.getByPath(taskName).getDependsOn().iterator().next();
-      Assert.assertEquals(1, taskProviders.size());
-      Assert.assertEquals(warTask, taskProviders.get(0).get());
+      TaskProvider<?> jibDependenciesTaskProvider =
+          (TaskProvider<?>) tasks.getByPath(taskName).getDependsOn().iterator().next();
+      Assert.assertEquals(jibDependenciesTaskProvider.get(), jibDependenciesTask);
```
Comment (seanabraham) [inline jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java]: These test changes (and the ones below) are now checking for whether the `jibDependencies` task depends on the requisite tasks (like the `warTask` or `bootWarTask` below) and whether all the jib tasks depend on `jibDependencies` which is the only task they need to depend on now.

**Comment by loosebazooka** [comment]
Nice, this is the better solution that #2246 . I'll take a deeper look in the next few days.

File: jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java [hunk 2]
```diff
@@ -162,68 +165,49 @@ public void apply(Project project) {
...
-                jar.setEnabled(true);
-                jar.getArchiveClassifier().set("original");
-              }
-            } else {
-              // Have all tasks depend on the 'classes' task.
-              dependsOnTask.add(projectAfterEvaluation.getTasks().named("classes"));
+          TaskProvider<Task> warTask = TaskCommon.getWarTaskProvider(projectAfterEvaluation);
+          TaskProvider<Task> bootWarTask =
+              TaskCommon.getBootWarTaskProvider(projectAfterEvaluation);
+          TaskProvider<Task> jibDependenciesTask = tasks.register("jibDependencies");
```
Comment (loosebazooka) [inline jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java]: I'll check when I can, but this doesn't show up in `gradlew tasks` does it?

File: jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java [hunk 3]
```diff
@@ -230,15 +171,24 @@ public void testWebAppProject_bootWar() {
...
     Task bootWarTask = tasks.getByPath(":bootWar");
+    Task jibDependenciesTask = tasks.getByPath(":jibDependencies");
     Assert.assertNotNull(warTask);
     Assert.assertNotNull(bootWarTask);
 
+    Set<Task> taskDependencies =
+        jibDependenciesTask
+            .getDependsOn()
+            .stream()
+            .filter(it -> it instanceof TaskProvider)
```
Comment (loosebazooka) [inline jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java]: we've been filtering like `.filter(TaskProvider.class::isInstance)`

File: jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java [hunk 4]
```diff
@@ -252,16 +202,25 @@ public void testWebAppProject_bootWarDisabled() {
...
+    Task jibDependenciesTask = tasks.getByPath(":jibDependencies");
     Assert.assertNotNull(warTask);
     Assert.assertNotNull(bootWarTask);
     bootWarTask.setEnabled(false); // should depend on bootWar even if disabled
 
+    Set<Task> taskDependencies =
+        jibDependenciesTask
+            .getDependsOn()
+            .stream()
+            .filter(it -> it instanceof TaskProvider)
```
Comment (loosebazooka) [inline jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java]: `filter(...` like above

**Comment by loosebazooka** [comment]
integ tests look good too.

File: jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java (hunk 2 above)
Comment (seanabraham) [reply jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java]: Though I can't remember what determines whether or not tasks show up in the `gradlew tasks` output, it doesn't look like it does in this case.

image

**Comment by seanabraham** [comment]
@loosebazooka thanks for the review! I addressed the comments, and confirmed that the `jibDependencies` task doesn't show up in the `gradlew tasks` output. Let me know if there are any other changes you'd like to see.

File: jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java (hunk 2 above)
Comment (loosebazooka) [inline jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java]: Can you use a const as above https://github.com/GoogleContainerTools/jib/pull/2247/files#diff-aef8bf567c91df6622aa0ea29ed0c682R53

```
JIB_DEPENDECIES_TASK_NAME="jibDependencies"
```

and then reuse it in `JibPluginTest.java`.

**Comment by loosebazooka** [comment]
@seanabraham thanks again. I think adding `jibDependencies` as an explicit task is not something we want to commit to at the moment. Could you just use the previous mechanism. I understand that the plugin logic and tests become more complicated, but the surface of jib exposed to the user is reduced.

File: jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java [hunk 5]
```diff
@@ -162,68 +166,49 @@ public void apply(Project project) {
...
-                jar.setEnabled(true);
-                jar.getArchiveClassifier().set("original");
-              }
-            } else {
-              // Have all tasks depend on the 'classes' task.
-              dependsOnTask.add(projectAfterEvaluation.getTasks().named("classes"));
+          TaskProvider<Task> warTask = TaskCommon.getWarTaskProvider(projectAfterEvaluation);
+          TaskProvider<Task> bootWarTask =
+              TaskCommon.getBootWarTaskProvider(projectAfterEvaluation);
+          TaskProvider<Task> jibDependenciesTask = tasks.register(DEPENDENCIES_TASK_NAME);
```
Comment (loosebazooka) [inline jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java]: Sorry, after thinking about this while we were doing the release, I realized I'm not quite convinced this is how we want to do this. Maybe in the future, the problem is going backwards/deprecating something has a high cost.

Can we just use the mechanism used previously: https://github.com/GoogleContainerTools/jib/pull/2247/files#diff-aef8bf567c91df6622aa0ea29ed0c682L175

Comment (seanabraham) [reply jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java]: Sure, I can make that change

**Comment by seanabraham** [comment]
@loosebazooka refactored to remove the `jibDependencies` task and instead have each of the jib tasks depend directly on relevant items (`war`, `bootWar`, etc. tasks and the runtimeClasspath configuration from the main source set)

**Comment by loosebazooka** [comment]
Awesome, thanks @seanabraham
