### PR TITLE
Makes sure all classes passed between async steps are immutable.

### LINKED ISSUE #276: Make sure all classes passed between async steps are immutable.
Looks like there was a `ConcurrentModificationException`: https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod%3Ajib%2Fgcp_ubuntu%2Fcontinuous

### PR DESCRIPTION
**Pull request by coollog**
Fixes #276

### CODE REVIEW

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/PullAndCacheBaseImageLayerStep.java [hunk 1]
```diff
@@ -46,7 +47,7 @@
       BuildConfiguration buildConfiguration,
       Cache cache,
       DescriptorDigest layerDigest,
-      Future<Authorization> pullAuthorizationFuture) {
```
Comment (TadCordle) [inline jib-core/src/main/java/com/google/cloud/tools/jib/builder/PullAndCacheBaseImageLayerStep.java]: Should probably change the private final field as well from `Future` to `ListenableFuture`

Comment (coollog) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/PullAndCacheBaseImageLayerStep.java]: Good catch - found a bunch of other places too
