### PR TITLE
fix: allow pushing images with different arch/os to docker daemon

### LINKED ISSUE #4265: Impossible to build amd-64 docker on Mac M3 machine
Starting 3.4.3 version of `jib-maven-plugin` it is not possible to build amd-64 image on Mac with Mx chip (arm-64)
I didn't find a setting, that fix it. There is no problem with 3.4.2 version.

### PR DESCRIPTION
**Pull request by mpeddada1**
Fixes #4265 and #4267
- Avoid throwing exception when building image with mismatched arch/os to the local docker daemon.
- Follow convention of using event handlers to log warning when building for matching os/arch. Example: https://github.com/GoogleContainerTools/jib/blob/b06b001ed26b6a1fedc1ac738f628513390433e9/jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java#L225

### CODE REVIEW

File: jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java [hunk 1]
```diff
@@ -343,27 +342,38 @@ public void testBasicMultiPlatform_toDockerDaemon()
...
-                    .containerize(
-                        Containerizer.to(
-                                DockerDaemonImage.named(
-                                    dockerHost + ":5000/docker-daemon-multi-platform"))
-                            .setAllowInsecureRegistries(true)));
-    assertThat(exception)
-        .hasCauseThat()
-        .hasMessageThat()
-        .startsWith("The configured platforms don't match the Docker Engine's OS and architecture");
+  public void testBasicMultiPlatform_toDockerDaemon_pickFirstPlatformWhenNoMatchingImage()
```
Comment (mpeddada1) [inline jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java:345]: TODO(@mpeddada1): Add test for single image build with different os/arch.

Comment (mpeddada1) [reply jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java:378]: Done in 9ff90bd4cf8aea53db7bfea31f7aa265550f5cd0

**Review by blakeli0 — APPROVED** [review]

**Comment by mpeddada1** [comment]
Notes on `kokoro-ubuntu` timeout:
- The job passed on https://github.com/GoogleContainerTools/jib/pull/4268/commits/f2d886b289a2e0d471f37281ce23322e00e6a288 but started failing after test for arm64 was added.

**Comment by chanseokoh** [comment]
@mpeddada1 just so you know, it sounds like #4267 is another issue introduced by #4249 in 3.4.3.

**Comment by mpeddada1** [comment]
> @mpeddada1 just so you know, it sounds like #4267 is another issue introduced by #4249 in 3.4.3.

Thank you @chanseokoh! Given that it is not reproducible in 3.4.2, the change in logging behavior may connected to some of the modifications made in https://github.com/GoogleContainerTools/jib/pull/4249. Will have to take a deeper look to understand what causes the difference in behavior for windows (perhaps in a separate dedicated PR).

**Comment by mpeddada1** [comment]
Regarding the integration test behavior on the CI:
- Changing test names is causing different behavior on the ubuntu CI. Documenting test names to better understand execution order: https://github.com/GoogleContainerTools/jib/pull/4268/commits/d92123d9675a3ea662c8c1a77e757bf003ffe0c6. According to https://github.com/junit-team/junit4/wiki/Test-execution-order#test-execution-order, Junit 4 uses deterministic but not predictable order.

**Comment by mpeddada1** [comment]
[Update on CI] Splitting the test methods up into separate test classes no longer causes the builds to be stuck. Ready for another round of review.

**Review by blakeli0 — APPROVED** [review]

**Comment by calebAtIspot** [comment]
should https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-specify-a-platform-in-the-manifest-list-or-oci-index-of-a-base-image be updated? It still says "Does not support pushing to a Docker daemon"
