### PR TITLE
Rethrow ExecutionException's cause in jib-core

### LINKED ISSUE #1440: Organize jib-core exceptions
At the moment, we wrap most of jib-core's errors and rethrow as `BuildStepsExecutionException`s with custom messages. For library users, it's somewhat vague which exceptions are thrown (since many are blanketed by `ExecutionException`) and why each exception is thrown, so it would be useful to either document this better, or somehow provide an easier way for more explicit exception handling.

### PR DESCRIPTION
**Pull request by TadCordle**
Fixes #1440 

Originally, it was up to the library user to catch an `ExecutionException`, and determine what kind of execution caused it using a series of `if (ex instanceof ...)` statements for more fine-grained exception handling. With this PR, `ExecutionException`s' causes are re-thrown if they are `RegistryException`s, which makes jib-core error handling/documentation much more straightforward.

### CODE REVIEW

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java [hunk 1]
```diff
@@ -226,53 +226,36 @@ public JibContainer build(
...
-            helpfulSuggestions.forCredentialsNotSent(), exceptionDuringBuildSteps);
+    } catch (RegistryCredentialsNotSentException ex) {
+      throw new BuildStepsExecutionException(helpfulSuggestions.forCredentialsNotSent(), ex);
 
-      } else if (exceptionDuringBuildSteps instanceof RegistryAuthenticationFailedException
-          && exceptionDuringBuildSteps.getCause() instanceof HttpResponseException) {
-        RegistryAuthenticationFailedException failureException =
-            (RegistryAuthenticationFailedException) exceptionDuringBuildSteps;
+    } catch (RegistryAuthenticationFailedException ex) {
+      if (ex.getCause() instanceof HttpResponseException) {
```
Comment (briandealwis) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java]: What happens if the cause isn't a `HttpResponseException`?

Comment (TadCordle) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java]: Ah right, I'll change it to match previous behavior.
