### PR TITLE
Fix main class finder missing main defined with varargs

### LINKED ISSUE #1456: MainClassFinder misses "public static void main(String... args)"
`public static void main(String... args)` is apparently a valid signature for the main method, but Jib doesn't find it.

### PR DESCRIPTION
**Pull request by TadCordle**
Fixes #1456

### CODE REVIEW

File: jib-core/src/main/java/com/google/cloud/tools/jib/frontend/MainClassFinder.java [hunk 1]
```diff
@@ -115,7 +115,8 @@ public Type getType() {
         Type.getMethodDescriptor(Type.VOID_TYPE, Type.getType(String[].class));
 
     /** Accessors that main may or may not have. */
-    private static final int OPTIONAL_ACCESS = Opcodes.ACC_FINAL | Opcodes.ACC_DEPRECATED;
+    private static final int OPTIONAL_ACCESS =
+        Opcodes.ACC_FINAL | Opcodes.ACC_DEPRECATED | Opcodes.ACC_VARARGS;
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/frontend/MainClassFinder.java]: Huh, it's weird that var args fall in the category of method access control.

File: jib-core/src/test/java/com/google/cloud/tools/jib/frontend/MainClassFinderTest.java [hunk 2]
```diff
@@ -126,4 +126,15 @@ public void testFindMainClass_innerClasses() throws URISyntaxException, IOExcept
...
         CoreMatchers.containsString("HelloWorld$InnerClass"));
   }
+
+  @Test
+  public void testMainClass_varargs() throws URISyntaxException, IOException {
+    Path rootDirectory =
+        Paths.get(Resources.getResource("core/class-finder-tests/varargs").toURI());
+    MainClassFinder.Result mainClassFinderResult =
+        new MainClassFinder(new DirectoryWalker(rootDirectory).walk(), mockEventDispatcher).find();
+    Assert.assertSame(Type.MAIN_CLASS_FOUND, mainClassFinderResult.getType());
```
Comment (chanseokoh) [inline jib-core/src/test/java/com/google/cloud/tools/jib/frontend/MainClassFinderTest.java]: Can't `assertEquals` work?

Comment (TadCordle) [reply jib-core/src/test/java/com/google/cloud/tools/jib/frontend/MainClassFinderTest.java]: It can, but we use "same" in most of the other `MainClassFinder` tests (`assertSame` tests using `==`, `assertEquals` tests using `.equals()`)
