### PR TITLE
Choose Base Distroless Java version based on project version

### LINKED ISSUE #1279: Intelligently pick Java 8 vs Java 11 distroless base image
From various sources and accounts, it seems that running applications compiled into Java 8 bytecode may fail to run on JVM 11.

Once we have the distroless Java 11, it may be desirable to intelligently match distroless 8 vs 11 based on the binary target version, instead of trying to use the latest JVM all the time.

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #1279.

I've spent a lot of time contemplating where would be the ideal place to do the validation if the user is using an incompatible base image. I ended up doing the check in the place where we have the logic to choose the base image, because otherwise, I thought we would be prone to miss updating both the image-choosing logic and the validation logic in a synchronized manner in the future when, e.g., Java 15 is introduced. That resulted in throwing an "incompatible base image" exception from `PluginConfigurationProgressor.getBaseImage()`.

### CODE REVIEW

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java [hunk 1]
```diff
@@ -289,16 +273,34 @@ static PluginConfigurationProcessor processCommonConfiguration(
    * @param rawConfiguration raw configuration data
    * @param projectProperties used for providing additional information
    * @return the base image
+   * @throws IncompatibleBaseImageJavaVersionException
```
Comment (TadCordle) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: Missing description (although doesn't matter that much since it's package private).

File: jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java [hunk 2]
```diff
@@ -170,6 +178,39 @@ public void testBuild_simple() throws IOException, InterruptedException, DigestE
     assertWorkingDirectory("/home", targetImage);
   }
 
+  @Test
+  public void testDockerDaemon_simpleOnJava11()
+      throws DigestException, IOException, InterruptedException {
+    Assume.assumeTrue(isJava11RuntimeOrHigher());
+
+    String targetImage = "localhost:6000/compleximage:gradle" + System.nanoTime();
```
Comment (coollog) [inline jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java]: nit: `simpleimage`?

File: jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-java11-incompatible.gradle [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+
+repositories {
+  mavenCentral()
+}
+
+dependencies {
+  compile files('libs/dependency-1.0.0.jar')
+}
+
+jib.from.image = 'gcr.io/distroless/java'
```
Comment (coollog) [inline jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-java11-incompatible.gradle]: Should we qualify this with the `8` tag? (In case we change `latest` to be Java 11 in the future)

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/IncompatibleBaseImageJavaVersionException.java [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
+ * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
+ * License for the specific language governing permissions and limitations under
+ * the License.
+ */
+
+package com.google.cloud.tools.jib.plugins.common;
+
+public class IncompatibleBaseImageJavaVersionException extends Exception {
```
Comment (coollog) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/IncompatibleBaseImageJavaVersionException.java]: nit: short javadoc

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java [hunk 5]
```diff
@@ -289,16 +273,34 @@ static PluginConfigurationProcessor processCommonConfiguration(
...
+
+    // Base image not configured; auto-pick Distroless.
+    if (projectProperties.isWarProject()) {
+      return "gcr.io/distroless/java/jetty";
+    } else if (javaVersion <= 8) {
+      return "gcr.io/distroless/java:8";
+    } else if (javaVersion <= 11) {
+      return "gcr.io/distroless/java:11";
+    } else {
+      throw new IncompatibleBaseImageJavaVersionException(11, javaVersion);
```
Comment (coollog) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: Should this use `11` as the `baseImageMajorJavaVersion`?

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java [hunk 6]
```diff
@@ -289,16 +273,34 @@ static PluginConfigurationProcessor processCommonConfiguration(
...
+  static String getBaseImage(RawConfiguration rawConfiguration, ProjectProperties projectProperties)
+      throws IncompatibleBaseImageJavaVersionException {
+    int javaVersion = projectProperties.getMajorJavaVersion();
+
+    if (rawConfiguration.getFromImage().isPresent()) {
+      String baseImage = rawConfiguration.getFromImage().get();
+
+      if (knownDistrolessJava8Image(baseImage) && javaVersion > 8) {
+        throw new IncompatibleBaseImageJavaVersionException(8, javaVersion);
+      } else if (knownDistrolessJava11Image(baseImage) && javaVersion > 11) {
```
Comment (coollog) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: nit: else's in this method not necessary

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java [hunk 7]
```diff
@@ -471,6 +473,45 @@ private static Path getCheckedCacheDirectory(String property, Path defaultPath)
...
+  /**
+   * Checks whether or not the known default Java 8 distroless base image is being used. Checking
+   * against only images known to Java 8, the method may to return {@code false} for Java 8
+   * distroless unknown to it.
+   *
+   * @param baseImageConfiguration the configured base image
+   * @return {@code true} if the base image is equal to one of the known Java 8 distroless images,
+   *     else {@code false}
+   */
+  private static boolean knownDistrolessJava8Image(String baseImageConfiguration) {
```
Comment (coollog) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: nit: `isKnownDistrolessJava8Image`?

Comment (coollog) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: nit: just `baseImage` since it's just a string?

File: jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java [hunk 8]
```diff
@@ -22,6 +22,7 @@
 import java.io.IOException;
 import java.security.DigestException;
 import java.time.Instant;
+import org.gradle.internal.impldep.com.google.api.client.repackaged.com.google.common.base.Splitter;
```
[the remark this answers is not in the document]
Comment (chanseokoh) [reply jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java]: Nice catch.

File: jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-java11-incompatible.gradle (hunk 3 above)
Comment (chanseokoh) [reply jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-java11-incompatible.gradle]: My idea was to leave the tag out so that if `latest` becomes Java 11, then builds will break and we will be immediately notified. When the switch happens, we will fix the test by qualifying this with the `8` tag, giving the chance to update other places that need attention.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java (hunk 5 above)
Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: We are auto-picking a base image and the highest available now is 11, so I thought saying 11 works here.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java (hunk 1 above)
Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: Will add. The exception class is not package-private, so makes sense to add it.

File: jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java [hunk 9]
```diff
@@ -170,6 +178,39 @@ public void testBuild_simple() throws IOException, InterruptedException, DigestE
...
+    try {
+      JibRunHelper.buildToDockerDaemonAndRun(
+          simpleTestProject, "willnotbuild", "build-java11-incompatible.gradle");
+      Assert.fail();
+
+    } catch (UnexpectedBuildFailure ex) {
+      Assert.assertThat(
+          ex.getMessage(),
+          CoreMatchers.containsString(
+              "The base image uses Java 8, but project is using Java 11, perhaps you should "
```
Comment (briandealwis) [inline jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java]: Trivial tweak:
> *your* project

But I wonder if flipping the order helps identify the mismatch:
> _Your project is using Java 11 but the base image is for Java 8.  Perhaps…_

File: jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java [hunk 10]
```diff
@@ -171,16 +171,7 @@ public void buildDocker()
...
-              + ex.getBaseImageMajorJavaVersion()
-              + ", but project is using Java "
-              + ex.getProjectMajorJavaVersion()
-              + "; perhaps you should configure a Java "
-              + ex.getProjectMajorJavaVersion()
-              + "-compatible base image using the 'jib.from.image' parameter, or set "
-              + "targetCompatibility = "
-              + ex.getBaseImageMajorJavaVersion()
-              + " or below in your build configuration");
+          HelpfulSuggestions.forIncompatibleBaseImageJavaVesionForGradle(8, 11));
```
Comment (coollog) [inline jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java]: Should this just take in the exception instead?

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java [hunk 11]
```diff
@@ -471,6 +476,45 @@ private static Path getCheckedCacheDirectory(String property, Path defaultPath)
...
+        || baseImage.equals("gcr.io/distroless/java:8")
+        || baseImage.equals("gcr.io/distroless/java:8-debug")
+        || baseImage.equals("gcr.io/distroless/java/jetty")
+        || baseImage.equals("gcr.io/distroless/java/jetty:debug")
+        || baseImage.equals("gcr.io/distroless/java/jetty:java8")
+        || baseImage.equals("gcr.io/distroless/java/jetty:java8-debug");
+  }
+
+  /**
+   * Checks whether or not the known default Java 11 distroless base image is being used. Checking
```
Comment (briandealwis) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: _Checks if the base image is a known Java 11 distroless image._?

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java [hunk 12]
```diff
@@ -471,6 +476,45 @@ private static Path getCheckedCacheDirectory(String property, Path defaultPath)
...
+   * Checks whether or not the known default Java 8 distroless base image is being used. Checking
+   * against only images known to Java 8, the method may to return {@code false} for Java 8
+   * distroless unknown to it.
+   *
+   * @param baseImage the configured base image
+   * @return {@code true} if the base image is equal to one of the known Java 8 distroless images,
+   *     else {@code false}
+   */
+  private static boolean isKnownDistrolessJava8Image(String baseImage) {
+    // TODO: drop "latest" and the likes once it no longer points to Java 8.
```
Comment (briandealwis) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: Since there's just `:debug` may as well list it explicitly (I think _like_ would be singular: _the like once they no longer_?)

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java [hunk 13]
```diff
@@ -471,6 +476,45 @@ private static Path getCheckedCacheDirectory(String property, Path defaultPath)
     return defaultPath;
   }
 
+  /**
+   * Checks whether or not the known default Java 8 distroless base image is being used. Checking
```
Comment (briandealwis) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: _Checks if the base image uses a known Java 8 distroless image._ is shorter.  I wasn't sure what "default" meant, especially since Jib doesn't use the `:debug` images ever.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java [hunk 14]
```diff
@@ -471,6 +476,45 @@ private static Path getCheckedCacheDirectory(String property, Path defaultPath)
...
+   * Checks whether or not the known default Java 11 distroless base image is being used. Checking
+   * against only images known to Java 11, the method may to return {@code false} for Java 11
+   * distroless unknown to it.
+   *
+   * @param baseImage the configured base image
+   * @return {@code true} if the base image is equal to one of the known Java 11 distroless images,
+   *     else {@code false}
+   */
+  private static boolean isKnownDistrolessJava11Image(String baseImage) {
+    // TODO: add "latest" and the likes once it points to Java 11.
```
Comment (briandealwis) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: There is no `latest` here

File: jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java (hunk 9 above)
Comment (chanseokoh) [reply jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java]: Sounds better. Unfortunately, `, perhaps you should` is the part automatically added by `HelpfulSuggestions.suggest()`, so can't fix here to use a dot.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java (hunk 13 above)
Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: Actually, I noticed this is a general method checking if the given image reference is a known distroless image. It doesn't have to be a base image. Reworded.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java (hunk 12 above)
Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: There are "jetty:debug" too. Noticed I missed "jetty:latest".

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java (hunk 11 above)
Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java]: Done. Also noticed the image doesn't have to be a base image. Fixed other minor things too.

File: jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java (hunk 10 above)
Comment (chanseokoh) [reply jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java]: I didn't like making this class depend on the exception class.

Comment (coollog) [reply jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java]: Should this at least take the versions from the exception instead of the hard-coded 8 and 11? Also, should prob add `ex` as the cause.

File: jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java [hunk 15]
```diff
@@ -262,20 +260,13 @@ public String getVersion() {
...
-    // maven-compiler-plugin default is 1.6
-    int version = 6;
-
+  @Override
+  public int getMajorJavaVersion() {
     // Check properties for version
     if (project.getProperties().getProperty("maven.compiler.target") != null) {
-      version = getVersionFromString(project.getProperties().getProperty("maven.compiler.target"));
+      return getVersionFromString(project.getProperties().getProperty("maven.compiler.target"));
     } else if (project.getProperties().getProperty("maven.compiler.release") != null) {
```
Comment (coollog) [inline jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java]: nit: These else's are not necessary as well

File: jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java (hunk 10 above)
Comment (chanseokoh) [reply jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java]: Gosh. Nice catch.

File: jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java [hunk 16]
```diff
@@ -165,6 +165,11 @@ public void buildTar()
     } catch (InvalidContainerVolumeException ex) {
       throw new GradleException(
           "container.volumes is not an absolute Unix-style path: " + ex.getInvalidVolume(), ex);
+
+    } catch (IncompatibleBaseImageJavaVersionException ex) {
+      throw new GradleException(
+          HelpfulSuggestions.forIncompatibleBaseImageJavaVesionForGradle(
+              ex.getBaseImageMajorJavaVersion(), ex.getProjectMajorJavaVersion()));
```
Comment (coollog) [inline jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java]: Also, maybe include `ex` as the cause for the `GradleException` for the stacktrace?

Comment (chanseokoh) [reply jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java]: We should. I missed it. Thanks.

**Comment by chanseokoh** [comment]
Will update CHANGELOG shortly.
