### PR TITLE
:zap: Gradle build optimizations

### LINKED ISSUE #3669: :zap:  Gradle build optimizations for this repository
**Environment**: Ubuntu 20.04

- *Jib version:* n/a
- *Build tool:* n/a
- *OS:* Ubuntu 20.04

**Description of the issue**:
Hi! I was analyzing the build for this project and found some optimizations that can be made to your Gradle build that would increase task cache hits. In order to accomplish this, I leveraged [this Gradle feature](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:meta_inf_normalization) and upgraded the Gradle wrapper to 6.6 (minimum version to leverage this feature). Today, when two subsequent `./gradle build` tasks are run on the same commit on the same machine, all the tests for all the submodules will be re-run.
**Expected behavior**:
Only modules that costume content that has changed will be re-run. 
**Steps to reproduce**:

  1. `./gradlew clean build`
  2. `./gradlew build`
  3.  Observe all tests are always rerun

Would you be open to receiving a change that improves this behavior in your build? Note, this would not impact consumers of artifacts that this repo publishes, only the build of this project.

### PR DESCRIPTION
**Pull request by ryandens**
fixes #3669 
Before filing a pull request, make sure to do the following:

- [x] Create a new issue at https://github.com/GoogleContainerTools/jib/issues/new/choose.
- [ ] Ensure that your implementation plan is approved by the team.
- [x] Verify that integration tests and unit tests are passing after the change.
- [x] Address all checkstyle issues. Refer to the [style guide](https://github.com/GoogleContainerTools/jib/blob/0ed7dca36864b6b19ff61629fc578018041fa15f/STYLE_GUIDE.md#style-guide).

This helps to reduce the chance of having a pull request rejected.

### CODE REVIEW

File: jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java [hunk 1]
```diff
@@ -137,7 +137,7 @@ public void testCheckJibVersionInvoked() {
     // Gradle tests aren't run from a jar and so don't have an identifiable plugin version
     assertThat(exception)
         .hasMessageThat()
-        .isEqualTo("Failed to apply plugin [id 'com.google.cloud.tools.jib']");
+        .isEqualTo("Failed to apply plugin 'com.google.cloud.tools.jib'.");
```
Comment (ryandens) [inline jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java:140]: this error message changed as a result of the gradle wrapper upgrade from 6.0.1 to 6.6.1

**Review by runningcode — APPROVED** [review]

**Review by elefeint — APPROVED** [review]
This is much faster, thank you!
