### PR TITLE
Fall back to initial authenticator if bad response

### LINKED ISSUE #2258: Tekton on OpenShift: authentication issue with internal OpenShift registry
From https://github.com/GoogleContainerTools/jib/issues/2074#issuecomment-579921534

> I did a new test using the following parameters top of ocp3 and that fails using jib-maven 2.0.0
>
> ```
>     - name: build-and-push
>       image: gcr.io/cloud-builders/mvn
>       command:
>         - mvn
>         - compile
>         - com.google.cloud.tools:jib-maven-plugin:2.0.0:build
>         - -Djib.from.image=registry.redhat.io/redhat-openjdk-18/openjdk18-openshift
>         - -Djib.allowInsecureRegistries=true
>         - -Djib.from.auth.username=my-user
>         - -Djib.from.auth.password=my-pwd
>         - -Dimage=$(outputs.resources.image.url)
> ```

> If I add to the config too `-DsendCredentialsOverHttp=true`, then we got this error
> ```
> [ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.0.0:build (default-cli) on project rest-http: 
> Build image failed: Failed to authenticate with registry docker-registry.default.svc:5000/test/sb-image 
> because: server did not return 'WWW-Authenticate: Bearer' header: Basic 
> realm=openshift,error="access denied" -> [Help 1]
> ```

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #2258.

If the server returns unexpected `WWW-Authenticate` responses  when attempting to refresh a bearer token, fall back to use the initial authenticator that succeeded to get the first token. `RegistryAuthenticator` is immutable and safe to reuse.

And fixing this will naturally make Jib to surface 401 eventually after 4 refresh attempts fail when the initial token did not have enough access scope.

### CODE REVIEW

File: jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java [hunk 1]
```diff
@@ -375,10 +378,13 @@ private Authorization refreshBearerAuth(@Nullable String wwwAuthenticate)
...
-        registry,
-        repository,
-        "server did not return 'WWW-Authenticate: Bearer' header: " + wwwAuthenticate);
+    eventHandlers.dispatch(
+        LogEvent.debug(
+            "server did not return 'WWW-Authenticate: Bearer' header. Actual: " + wwwAuthenticate));
+    if (readOnlyBearerAuth) {
+      return Verify.verifyNotNull(initialBearerAuthenticator.get()).authenticatePull(credential);
+    }
+    return Verify.verifyNotNull(initialBearerAuthenticator.get()).authenticatePush(credential);
```
Comment (TadCordle) [inline jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java]: Would it be worth it to pull this out into a function to reduce duplication between here and L374-377?

File: jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java [hunk 2]
```diff
@@ -168,6 +169,71 @@ public void testAutomaticTokenRefresh()
...
+    RegistryClient registryClient = createRegistryClient(null);
+    Assert.assertTrue(registryClient.doPushBearerAuth());
+
+    try {
+      registryClient.checkBlob(digest);
+      Assert.fail("Should have given up refreshing after 4 attempts");
+    } catch (RegistryUnauthorizedException ex) {
+      Assert.assertEquals(401, ex.getHttpResponseException().getStatusCode());
+      Assert.assertEquals(5, authServer.getTotalResponsesServed());
+      Assert.assertEquals(6, registry.getTotalResponsesServed());
```
Comment (briandealwis) [inline jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java]: Should this be 5? (1 successful, and then 4 attempts)?

File: jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java [hunk 3]
```diff
@@ -344,6 +346,7 @@ private boolean doBearerAuth(boolean readOnlyBearerAuth) throws IOException, Reg
       return false; // server returned "WWW-Authenticate: Basic ..."
     }
 
+    initialBearerAuthenticator.set(authenticator.get());
```
[the remark this answers is not in the document]
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java]: Should be okay, since `refreshBearerAuth` is designed in the way that it's called only when `authorization` is a bearer auth token.

File: jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java (hunk 1 above)
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java]: I think this is fine, considering that there's a difference between `authenticator` and `initialBearerAuthenticator` that the latter is nullable.

File: jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java (hunk 2 above)
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java]: It's 6: 1 response asking to auth + 4 unauth responses for 4 refresh attempts + 1 final unauth response that will be thrown as `RegistryUnauthorizedException`. I'll put a comment in the code.

**Comment by chanseokoh** [comment]
Oops, will add a CHANGELOG entry.
