### PR TITLE
Fix parsing auth block in maven plugin

### LINKED ISSUE #809: Error when putting <auth> in pom.xml
From https://github.com/GoogleContainerTools/jib/issues/808#issuecomment-411225404

This worked in 0.9.8, so this is a regression.
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.9-SNAPSHOT:build (default-cli) on project helloworld: Unable to parse configuration of mojo com.google.cloud.tools:jib-maven-plugin:0.9.9-SNAPSHOT:build for parameter auth: Cannot create instance of class com.google.cloud.tools.jib.maven.JibPluginConfiguration$AuthConfiguration: com.google.cloud.tools.jib.maven.JibPluginConfiguration$AuthConfiguration.<init>() -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigurationException
```
Gradle works OK though.

### PR DESCRIPTION
**Pull request by TadCordle**
Fixes #809

### CODE REVIEW

File: jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java [hunk 1]
```diff
@@ -82,6 +67,21 @@ public String getUsername() {
...
+    void setUsername(String username) {
+      this.username = username;
+    }
+
+    @VisibleForTesting
+    void setPassword(String password) {
+      this.password = password;
+    }
+
+    private void setPropertyDescriptors(String usernameDescriptor, String passwordDescriptor) {
```
Comment (coollog) [inline jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java]: This can be like the constructor and just take a single `descriptor` right?
