### PR TITLE
Only warn if inferred credential helper threw NonexistentServerUrlDockerCredentialHelperException

### LINKED ISSUE #827: Don't fail credential retrieval if inferred credential helper threw NonexistentServerUrlDockerCredentialHelperException.
From https://github.com/GoogleContainerTools/jib/pull/825#discussion_r209344161

### PR DESCRIPTION
**Pull request by TadCordle**
Fixes #827

### CODE REVIEW

File: jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java [hunk 1]
```diff
@@ -171,17 +171,17 @@ CredentialRetriever inferCredentialHelper(
                       + inferredCredentialHelperSuffix),
               dockerCredentialHelperFactory);
 
-        } catch (DockerCredentialHelperNotFoundException ex) {
+        } catch (DockerCredentialHelperNotFoundException
+            | NonexistentServerUrlDockerCredentialHelperException ex) {
```
Comment (loosebazooka) [inline jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java]: How does this failure now affect the build? Just it just continue to some other auth mechanism?

Comment (TadCordle) [reply jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java]: Yeah, currently if the first cred helper exists, but doesn't have the correct server url, it'll just fail without checking other cred helpers on the system. So now it will treat cred helpers that are missing the correct url the same way we've been treating missing cred helpers.
