### PR TITLE
Do not crash on inaccurate progress reporting

### LINKED ISSUE #1512: jib:build Remaining allocation units less than 0
**Description of the issue**:
The jib-maven-plugin failed with this error message:
`org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.0.1:build (default-cli) on project backend: Remaining allocation units less than 0 for 'pull container configuration sha256:0ea51d9f12788eb9ab2fad601aeda6fd2d444fde75b1cfb853994913ed88243d': -1`

I use Nexus 3 as a local Docker repository for my images, and as a proxy to Docker Hub.
In front of Nexus, I have a Traefik, which setup itself from Docker labels.

The docker labels of the Nexus repository:
- traefik.docker.network=public
- traefik.frontend.entryPoints=http,https
- traefik.app.port=8081
- traefik.app.frontend.rule=Host:nexus.192.168.100.101.nip.io
- traefik.registry_pull.port=5055
- traefik.registry_pull.frontend.rule=Host:nexus.192.168.100.101.nip.io;PathPrefix:/v2;Method: GET
- traefik.registry_pull.priority=30
- traefik.registry_push_1.port=5050
- traefik.registry_push_1.frontend.rule=Host:nexus.192.168.100.101.nip.io; PathPrefix:/v2
- traefik.registry_push_1.priority=20
- traefik.registry_push_2.port=5050
- traefik.registry_push_2.frontend.rule=Host:nexus.192.168.100.101.nip.io; PathPrefix:^/(v1|v2)/[^/]+/?[^/]+/blobs/;Method: POST, PUT, PATCH, DELETE, HEAD
- traefik.registry_push_2.priority=40

With this configuration, the `docker pull nexus.192.168.100.101.nip.io/alpine:latest` and others work as expected, but jib cannot pull docker layers.
If a publish the port 5050, 5055, and configure jib to pull and push from/to these ports, then jib works as expected.

**Environment**:
Build from Jenkins Pipeline with Docker Maven container (maven:3-jdk-11-slim)

**`jib-maven-plugin` Configuration (relevant section)**: 
```xml
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>jib-maven-plugin</artifactId>
	<version>1.0.1</version>
	<configuration>
		<allowInsecureRegistries>true</allowInsecureRegistries>
		<from>
			<!--suppress UnresolvedMavenProperty -->
			<image>${nexus.location}/adoptopenjdk/openjdk11:alpine</image>
		</from>
		<to>
			<!--suppress UnresolvedMavenProperty -->
			<image>${nexus.location}/mekh/phonebook-backend:${project.version}</image>
		</to>
		<container>
			<ports>
				<port>8080</port>
			</ports>
		</container>
	</configuration>
</plugin>
```

**Additional Information**: 
The jib-maven-plugin:1.0.0 can use HTTP, but the jib-maven-plugin:1.0.1 works with only HTTPS connection.

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes https://github.com/GoogleContainerTools/jib/issues/1512#issuecomment-468333807, where the root cause is believed to be an inaccurate or missing `Content-Length` value. (The log shows that `remainingAllocationUnits` is -1 when the `Verify` statement is violated.)

Closes #1512.

### CODE REVIEW

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcher.java [hunk 1]
```diff
@@ -62,8 +61,11 @@ ProgressEventDispatcher create(
    */
   public static ProgressEventDispatcher newRoot(
       EventDispatcher eventDispatcher, String description, long allocationUnits) {
+    long allocationUnitsChecked = allocationUnits < 0 ? 0 : allocationUnits;
```
Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcher.java]: We could probably just move this to the constructor for `Allocation`.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcher.java [hunk 2]
```diff
@@ -139,18 +144,20 @@ public void close() {
...
    */
   public void dispatchProgress(long progressUnits) {
-    decrementRemainingAllocationUnits(progressUnits);
-    eventDispatcher.dispatch(new ProgressEvent(allocation, progressUnits, buildStepType));
+    long unitsDecremented = decrementRemainingAllocationUnits(progressUnits);
+    eventDispatcher.dispatch(new ProgressEvent(allocation, unitsDecremented, buildStepType));
   }
 
-  private void decrementRemainingAllocationUnits(long units) {
+  private long decrementRemainingAllocationUnits(long units) {
```
Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcher.java]: nit: Let's add a short javadoc describing the return value
