### PR TITLE
Make DefaultCacheStorageWriter.moveIfDoesNotExist() more robust to concurrency

### LINKED ISSUE #1273: [gradle] Concurrency issue with many simultaneous builds
**Description of the issue**: In a project that can run dozens of jib build tasks concurrently, an exception was thrown when working with the cache

```
Step #3 - "curio-generated-build-all": Caused by: com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build image failed
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build(BuildStepsRunner.java:269)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:119)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #3 - "curio-generated-build-all": at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
Step #3 - "curio-generated-build-all": ... 133 more
Step #3 - "curio-generated-build-all": Caused by: java.nio.file.FileSystemException: /root/.cache/google-cloud-tools-java/jib/tmp/10954747174794241924 -> /root/.cache/google-cloud-tools-java/jib/layers/096ebeedeeb6534eadf6d1ae8173145e8f43aedf29f5ae179f8b2e899f84f344: Directory not empty
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorageWriter.moveIfDoesNotExist(DefaultCacheStorageWriter.java:75)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorageWriter.write(DefaultCacheStorageWriter.java:154)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorage.write(DefaultCacheStorage.java:74)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.Cache.writeCompressedLayer(Cache.java:68)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:81)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:36)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
Step #3 - "curio-generated-build-all": 
```

**Expected behavior**: The build succeeds

**Steps to reproduce**:  This only happens sometimes, and on a build with dozens of projects. I suspect it will be hard to reproduce with a small build.

**Environment**: Linux, Gradle 5.0-rc-4, Java 11, gradle-jib-plugin 0.10.0

**`jib-gradle-plugin` Configuration**: 

Standard configuration, just lots of subprojects

**Log output**:

```
Step #3 - "curio-generated-build-all": Caused by: com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build image failed
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build(BuildStepsRunner.java:269)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:119)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #3 - "curio-generated-build-all": at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
Step #3 - "curio-generated-build-all": ... 133 more
Step #3 - "curio-generated-build-all": Caused by: java.nio.file.FileSystemException: /root/.cache/google-cloud-tools-java/jib/tmp/10954747174794241924 -> /root/.cache/google-cloud-tools-java/jib/layers/096ebeedeeb6534eadf6d1ae8173145e8f43aedf29f5ae179f8b2e899f84f344: Directory not empty
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorageWriter.moveIfDoesNotExist(DefaultCacheStorageWriter.java:75)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorageWriter.write(DefaultCacheStorageWriter.java:154)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorage.write(DefaultCacheStorage.java:74)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.Cache.writeCompressedLayer(Cache.java:68)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:81)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:36)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
Step #3 - "curio-generated-build-all": 
```

**Additional Information**: 

The OS is Linux (more specifically Google's Cloud Build VM with a build image based on debian), so I think atomic moves should work and would not expect #1044 to be related.

### PR DESCRIPTION
**Pull request by briandealwis**
`DefaultCacheStorageWriter.moveIfDoesNotExist()` uses `Files.move()` to move a cache-layer into place.  The implementation first attempted to perform an atomic rename, but should that operation error in certain ways then it would retry the move as a copy-and-delete.  But it turns out that (1) the underlying primitives may throw other hard-to-enumerate platform-specific exceptions, which we were not catching, and which may be thrown in a concurrency situation where two jobs are attempting to install the same cache-layer, and (2) `Files.move()` does a copy-and-delete when required.  

So this patch changes the code to just perform a `Files.move()` and lets the implementation do its best.  If an exception is raised but the destination directory now exists, then the implementation ignores the exception and treats it as a symptom of a concurrent installation.

Fixes #1273

### CODE REVIEW

**Comment by briandealwis** [comment]
I mentioned I'd try to log the error, but getting a logger into this code is difficult.  And if there is a problem then it should be picked up as a cache corruption problem.

File: jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageWriter.java [hunk 1]
```diff
@@ -67,35 +64,18 @@ private WrittenLayer(
...
-      } catch (DirectoryNotEmptyException ex) {
-        // The file system cannot rename directories, so we must resort to copying the directory.
-        Files.createDirectory(destination);
-        try (Stream<Path> sourceFiles = Files.list(source)) {
-          for (Path sourceFile : sourceFiles.collect(Collectors.toList())) {
-            Files.copy(sourceFile, destination.resolve(sourceFile.getFileName()));
-          }
-        }
+    } catch (FileSystemException ex) {
+      if (!Files.exists(destination)) {
```
Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageWriter.java]: Perhaps add a TODO to log the destination exists in the future or something about this ignored the `FileSystemException` if the `destination` exists.
