### PR TITLE
Fix lock file failures

### LINKED ISSUE #1695: LockFileTest failure
Looking at the test, because the integer update is not an atomic get-and-set, ~~I think it's prone to failure.~~

```
[INFO] Running com.google.cloud.tools.jib.filesystem.LockFileTest
Exception in thread "Thread-1" java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.google.cloud.tools.jib.filesystem.LockFileTest.lambda$testLockAndRelease$0(LockFileTest.java:41)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.117 s <<< FAILURE! - in com.google.cloud.tools.jib.filesystem.LockFileTest
[ERROR] testLockAndRelease(com.google.cloud.tools.jib.filesystem.LockFileTest)  Time elapsed: 0.115 s  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.google.cloud.tools.jib.filesystem.LockFileTest.testLockAndRelease(LockFileTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

### PR DESCRIPTION
**Pull request by TadCordle**
Fixes #1695.

- No longer deletes lock file. This was causing a race condition where one thread could release a lock, another thread could acquire a lock, and then the first thread would delete the lock file, which caused the test to fail.
- Saves a reference to the original lock file output stream to prevent it from being garbage collected/closed/releasing the file lock acquired from it.

### CODE REVIEW

**Comment by TadCordle** [comment]
Same results, sort of. Windows fails to delete because the file is open by another process, linux and mac successfully delete while the file is locked.

File: jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/LockFile.java [hunk 1]
```diff
@@ -73,10 +73,16 @@ public void close() {
...
         Files.delete(lockFile);
 
-      } catch (IllegalMonitorStateException | IOException ignored) {
+      } catch (IOException ignored) {
+
+      } finally {
+        try {
+          Preconditions.checkNotNull(lockMap.get(lockFile)).unlock();
+
+        } catch (IllegalMonitorStateException ignored) {
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/LockFile.java]: Ah, I think I was wrong with catching this, sorry. I mistakenly assumed that `LockFile.close()` will be called if `ReentrantLock.lockInterruptibly()` fails in the static `LockFile.lock()` constructor. The `LockFile` instance is never instantiated in that case, so I think `IllegalMonitorStateException` can never happen. Agreed?

**Comment by TadCordle** [comment]
I think this can be reviewed now, I believe it should fix the flakiness from our test/prevent some other future problems.

File: jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/LockFile.java [hunk 2]
```diff
@@ -58,26 +61,31 @@ public static LockFile lock(Path lockFile) throws IOException {
...
+      }
+    }
   }
 
   /** Releases the lock file. */
   @Override
   public void close() {
     try {
       fileLock.release();
+      outputStream.close();
```
Comment (briandealwis) [inline jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/LockFile.java]: I missed this fun somehow yesterday, but closing the stream closes the channel, and closing the channel releases the lock.

Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/LockFile.java]: Yeah, we figured that out, but we decided to release it explicitly as we hold both references anyways and to eliminate a potential doubt for future readers.
