### PR TITLE
remove deprecation warnings

### LINKED ISSUE #2086: Issues with Gradle 6.0-rc-1
**Environment**:

- *Jib version:* 1.7.0
- *Build tool:* Gradle 6.0-rc-1
- *OS:* Windows 10 Enterprise

**Description of the issue**:
When I invoke `gradle jib` I get these deprecation warnings:

```
> Task :jib
Property 'jib.allowInsecureRegistries' @Input properties with primitive type 'boolean' cannot be @Optional. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'jib.container.useCurrentTimestamp' @Input properties with primitive type 'boolean' cannot be @Optional. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
```

**Expected behavior**:
No deprecation warning

**Steps to reproduce**:
see above

**Log output**: 
see abouve

### PR DESCRIPTION
**Pull request by glefloch**
close #2086 by removing deprecated `@org.gradle.api.tasks.Optional` annotation

### CODE REVIEW

File: jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java [hunk 1]
```diff
@@ -192,7 +192,6 @@ public OutputPathsParameters getOutputPaths() {
   }
 
   @Input
-  @Optional
```
Comment (loosebazooka) [inline jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java]: I don't know if we have defaults for this parameter, like we do for `useCurrentTimestamp`. Its instantiated with
```	
allowInsecureRegistries = objectFactory.property(Boolean.class);
```

**Comment by chanseokoh** [comment]
But we set the default.

```java
    allowInsecureRegistries = objectFactory.property(Boolean.class);
    containerizingMode = objectFactory.property(String.class);

    // Sets defaults.
    allowInsecureRegistries.set(DEFAULT_ALLOW_INSECURE_REGISTIRIES);
    containerizingMode.set(DEFAULT_CONTAINERIZING_MODE);
```

I'll do an actual testing to make sure these are by default true.
