### PR TITLE
Ensure internally-created executor service is shutdown on completion

### LINKED ISSUE #1310: jib-core: shut down executor service to allow JVM termination
Was testing jib-core.

```java
  public static void main(String[] args) throws Exception {
    Containerizer containerizer = Containerizer.to(DockerDaemonImage.named("francium25/test"));
    Jib.from("francium25/base").containerize(containerizer);
  }
```

The code does not terminate after the image is built, because we are not shutting down `StepsRunner.listeningExecutorService`. One potential-but-not-really-right way to handle it would be to shut it down in `waitOn...Step()`, which is the last step of the `Steps` we chain.

From the perspective of the above simple code, it makes sense to shut it down. However, it's possible to accept an executor service from the user via `Containerizer.setExecutorService()`, and we shouldn't shut their service down on our discretion at the end. But we could accept another parameter for `setExecutorService()` to tell us if we will shut it down or not.

Also, another consequence of shutting down the service is that, in the usual case where people don't provide their executor service, they cannot reuse `JibContainerBuilder`.
```java
    JibContainerBuilder cb = Jib.from(...);
    cb.containerize(...);
    cb.containerize(...); // exception because the executor service is shut down.
```
This is because `BuildConfiguration` is owned by `JibContainerBuilder`, hence the two `containerize()` calls share `executorService`, which `BuildConfiguration` owns. And `executorService` is a mutable object.

And the problem is that, as long as we allow reusing `JibContainerBuilder`, it is impossible to know when it is OK to shut it down.

### PR DESCRIPTION
**Pull request by briandealwis**
Ensure that internally-created `ExecutorService` is shutdown.

Fixes #1310

### CODE REVIEW

File: jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java [hunk 1]
```diff
@@ -441,9 +462,8 @@ BuildConfiguration toBuildConfiguration(Containerizer containerizer)
         .setContainerConfiguration(containerConfigurationBuilder.build())
         .setLayerConfigurations(layerConfigurations)
         .setAllowInsecureRegistries(containerizer.getAllowInsecureRegistries())
-        .setToolName(containerizer.getToolName());
-
-    containerizer.getExecutorService().ifPresent(buildConfigurationBuilder::setExecutorService);
+        .setToolName(containerizer.getToolName())
+        .setExecutorService(executorService);
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java]: Should we remove the code calling `newCachedThreadPool()` in `BuildConfiguration`, and return an error if the executor is not set? (`BuildConfiguration` is not public-facing.)

```
          if (executorService == null) {
            executorService = Executors.newCachedThreadPool();
          }
```

File: jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java [hunk 2]
```diff
@@ -58,6 +61,9 @@
 // TODO: Add tests once containerize() is added.
 public class JibContainerBuilder {
 
+  @VisibleForTesting
+  static Supplier<ExecutorService> executorServiceFactory = Executors::newCachedThreadPool;
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java]: Personally, I try avoiding swapping out a field for testing particularly for a static field (or it is just me thinking this way?), but I guess there is no other better way.

File: jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java (hunk 1 above)
Comment (briandealwis) [reply jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java]: Oops, that had been removed, but I reworked the patch and it was restored.

File: jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java (hunk 2 above)
Comment (briandealwis) [reply jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java]: Just realized a better approach.

File: jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java [hunk 3]
```diff
@@ -417,21 +420,45 @@ public JibContainerBuilder setWorkingDirectory(@Nullable AbsoluteUnixPath workin
...
-    BuildConfiguration buildConfiguration = toBuildConfiguration(containerizer);
-    BuildResult result = containerizer.getTargetImage().toBuildSteps(buildConfiguration).run();
-    return new JibContainer(result.getImageDigest(), result.getImageId());
+
+    return containerize(containerizer, Executors::newCachedThreadPool);
+  }
+
+  @VisibleForTesting
+  JibContainer containerize(
+      Containerizer containerizer, Supplier<ExecutorService> executorServiceFactory)
```
Comment (loosebazooka) [inline jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java]: Would consider a different name for this `executorServiceFactory` since it's just a backup/default.

File: jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java [hunk 4]
```diff
@@ -417,21 +420,45 @@ public JibContainerBuilder setWorkingDirectory(@Nullable AbsoluteUnixPath workin
...
+    ExecutorService executorService =
+        containerizer.getExecutorService().orElseGet(executorServiceFactory);
+
+    BuildConfiguration buildConfiguration = toBuildConfiguration(containerizer, executorService);
+
+    try {
+      BuildResult result = containerizer.getTargetImage().toBuildSteps(buildConfiguration).run();
+      return new JibContainer(result.getImageDigest(), result.getImageId());
+    } finally {
+      if (shutdownExecutorService) {
```
Comment (loosebazooka) [inline jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java]: Could we control the lifecycle with an `Consumer<ExecutorService> cleanup` option?

I'm having a hard time visualizing it though, so maybe we shouldn't.

File: jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java (hunk 3 above)
Comment (loosebazooka) [reply jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java]: maybe the method needs to be renamed to indicate the `Supplier` is an or else kind of situation?

File: jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java [hunk 5]
```diff
@@ -141,7 +156,9 @@ public void testToBuildConfiguration()
     JibContainerBuilder jibContainerBuilder =
         new JibContainerBuilder(baseImage, spyBuildConfigurationBuilder)
             .setLayers(Arrays.asList(mockLayerConfiguration1, mockLayerConfiguration2));
-    BuildConfiguration buildConfiguration = jibContainerBuilder.toBuildConfiguration(containerizer);
+    BuildConfiguration buildConfiguration =
+        jibContainerBuilder.toBuildConfiguration(
+            containerizer, containerizer.getExecutorService().get());
```
[the remark this answers is not in the document]
Comment (briandealwis) [reply jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java]: The test is checking that the set values are actually propagated into the `BuildConfiguration`.  Using `Optional.get()` here will thrown an exception if the `Containerizer` wasn't configured with an `ExecutorService`, and also ensures that the resulting `BuilkdConfiguration` has the configured `ExecutorService`.

File: jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java (hunk 4 above)
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java]: I think `try ... finally` works. (I'm assuming the `run()` is blocking, which I believe is true.)

Comment (briandealwis) [reply jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java]: The `run()` is somewhat-blocking, in that we [wait on the future from the final step](https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java#L276), but `shutdown()` triggers an orderly shutdown that will continue any pending work until completion.

Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java]: > somewhat-blocking,

I'd say it's sure-blocking. :)
