### PR TITLE
Advanced configuration avoidance (jib-gradle-plugin)

### LINKED ISSUE #2072: Jib Gradle plugin creating tasks even when not run
**Environment**:

- *Jib version:* v1.6.2-SNAPSHOT >
- *Build tool:* Gradle 5.2.1
- *OS:* MacOS

**Description of the issue**:
When running `gradle help` and you use the `jib-gradle-plugin` all the jib related tasks are created during configuration instead during execution.

image

**Expected behavior**:
Running `gradle help` should not create any jib related task.

**Steps to reproduce**:

  1. gradle help

### PR DESCRIPTION
**Pull request by slowr**
Avoid creating jib tasks (also dependents like jar, assemble, war, etc) when not needed.

Before,
image

After,
image

Resolves #2072

### CODE REVIEW

**Comment by slowr** [comment]
It seems that current `GRADLE_MIN_VERSION` is set to `4.6` which does not support `TaskProvider`.

I bumped the minimum version to `4.9` which introduced `TaskProvider` but this seems to be a major change.

**Comment by loosebazooka** [comment]
4.9 is quite old, I don't think we have to worry too much about it. We can bump that number

File: jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java [hunk 1]
```diff
@@ -38,20 +39,20 @@
...
-    if (project.getPlugins().hasPlugin("org.springframework.boot")) {
-      Task bootWar = project.getTasks().findByName("bootWar");
-      if (bootWar != null) { // Spring Boot > 2.0
-        return (War) bootWar;
+    try {
+      if (project.getPlugins().hasPlugin("org.springframework.boot")) {
+        return project.getTasks().named("bootWar");
       }
+      return project.getTasks().named(WarPlugin.WAR_TASK_NAME);
+    } catch (UnknownTaskException ignored) {
```
Comment (loosebazooka) [inline jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java]: I think the order is wrong here? catch should happen somewhere else? Or if we never intended to come here we should throw an illegal state exception or something.

Since we already checked if the `war-plugin` exists on the project, we should by default return `war` task.

Comment (chanseokoh) [reply jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java]: Ah, nice catch.

Comment (slowr) [reply jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java]: I just put the `named('war')` inside the try..catch block to make sure I always handle the exception it throws when the task is not there. 

In this case it should never be triggered _unless_ the war task name is changed so I wanted to be safe.

Should I move it outside of the try..catch block?

Comment (chanseokoh) [reply jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java]: If `named("bootWar")` can throws the exception, which I think is a real possibility, this method should return `named("war")` instead of null, shouldn't it?

Comment (slowr) [reply jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java]: oh I see what you mean.. in case that the project has `org.springframework.boot` plugin but not `bootWar` task then it will return null while there is a possibility that there is a `war` task as well (because of the warplugin check above). I will move the return outside the try..catch and remove the null return.
