### PR TITLE
Prevent sending multiple requests in a connection

### LINKED ISSUE #686: Connection should explicitly prevent reusing (should not allow sending multiple Requests)
The Javadoc says "Make sure to wrap with a try-with-resource to ensure that the connection is closed after usage." This is to call `disconnect()` on `httpResponse`.

```java
  public void close() throws IOException {
    ...
    httpResponse.disconnect();
  }
```
However, the field `httpResponse` is replaced every time a request is sent. The references to old `httpResponse`s will be lost with multiple sends.

```java
  public Response send(String httpMethod, Request request) throws IOException {
    ...
    httpResponse = httpRequest.execute();
    return new Response(httpResponse);
  }
```

Or, alternatively, the class could be extended to allow reusing, but I think this may become YAGNI, so I prefer having the code simple.

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #686.

Had to remove the `@Mock` annotation from the `httpResponse` field, since otherwise it is injected into `Connection` by `@InjectMocks`.

Also added another test class for `Connection` that interacts with a local web server.

### CODE REVIEW

File: jib-core/src/main/java/com/google/cloud/tools/jib/http/Connection.java [hunk 1]
```diff
@@ -23,23 +23,25 @@
...
 
 /**
- * Sends an HTTP {@link Request} and stores the {@link Response}.
+ * Sends an HTTP {@link Request} and stores the {@link Response}. Clients should not send more than
+ * one request.
  *
  * <p>Example usage:
  *
- * <pre>{@code
+ * <pre>
```
Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/http/Connection.java]: I believe the `{@code` is the recommended way of wrapping multi-line code blocks. (https://stackoverflow.com/a/542142/10047775)

File: jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfig.java [hunk 2]
```diff
@@ -106,7 +106,7 @@ DockerCredentialHelper getCredentialHelperFor(String registry) {
   DockerCredentialHelper getCredentialHelperFor(
       DockerCredentialHelperFactory dockerCredentialHelperFactory, String registry) {
     List<Predicate<String>> registryMatchers = getRegistryMatchersFor(registry);
-    Map.Entry<String, AuthTemplate> firstMatchInAuths =
+    Map.Entry<String, ?> firstMatchInAuths =
```
Comment (coollog) [inline jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfig.java]: Was this intentional?

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+/** Tests for {@link Connection} using an actual local server. */
+public class WithServerConnectionTest {
+
+  private static class WebServer implements Closeable {
+
+    private ServerSocket serverSocket;
+    private boolean stop;
+
+    private WebServer() throws IOException {
+      serverSocket = new ServerSocket(8087);
```
Comment (coollog) [inline jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java]: Should we use a 5-digit port here for less chance of collisions?

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java [hunk 4]
```diff
@@ -0,0 +1,89 @@
...
+import org.junit.Assert;
+import org.junit.Test;
+
+/** Tests for {@link Connection} using an actual local server. */
+public class WithServerConnectionTest {
+
+  private static class WebServer implements Closeable {
+
+    private ServerSocket serverSocket;
+    private boolean stop;
```
Comment (coollog) [inline jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java]: This will probably need to be `volatile`

Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java]: Ah, you're right.

File: jib-core/src/main/java/com/google/cloud/tools/jib/http/Connection.java (hunk 1 above)
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/http/Connection.java]: TIL

**Comment by chanseokoh** [comment]
Just noticed I am not waiting until the server is properly up.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java (hunk 3 above)
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java]: I'll just let it pick up any available port.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java (hunk 4 above)
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java]: Turns out the field isn't needed at all, since `accept()` will throw an exception once `serverSocket` is closed, terminating the loop.

File: jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfig.java (hunk 2 above)
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfig.java]: Did not really intend, but I guess we can have it here as a trivial cleanup. Signifies that the value is not being used, and the added benefit of less cramped code.

Comment (coollog) [reply jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfig.java]: kk sounds good

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+        }
+      }
+      Thread.sleep(50);
+    }
+    Thread.currentThread().interrupt();
+  }
+
+  private void serve200() {
+    try {
+      while (true) {
```
Comment (coollog) [inline jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: I think you could do a `wait/notify` for this rather than the 50ms thread sleep and remove the `waitUntilReady` method.

**Comment by chanseokoh** [comment]
Windows is kind of weird. Could be the CRLF incompatibility, or perhaps I need keep the connection alive.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+
+import java.io.Closeable;
+import java.io.IOException;
+import java.io.OutputStream;
+import java.net.ServerSocket;
+import java.net.Socket;
+import java.nio.charset.StandardCharsets;
+
+/** Simple local web server for testing. */
+public class TestWebServer implements Closeable {
```
Comment (coollog) [inline jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: nit: could be package-private (and methods)

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java [hunk 7]
```diff
@@ -59,10 +68,10 @@ private void waitUntilReady() throws IOException, InterruptedException {
   private void serve200() {
     try {
       while (true) {
-        try (Socket socket = serverSocket.accept();
-            OutputStream out = socket.getOutputStream()) {
-          out.write("HTTP/1.1 200 OK\n\nHello World!".getBytes(StandardCharsets.UTF_8));
-        }
+        Socket socket = serverSocket.accept();
+        sockets.add(socket);
+        OutputStream out = socket.getOutputStream();
```
Comment (coollog) [inline jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: I think the issue is that the `OutputStream` needs to be closed first.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java (hunk 5 above)
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: I wanted to make sure `serverSocket.accept()` is reached, instead of notifying just before calling `accept()`.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java (hunk 7 above)
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: I don't really think so... closing socket should just close anything underneath it gracefully. Anyway, the test is now passing, so I think my theory about keep-alive seems right.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java (hunk 5 above)
Comment (coollog) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: Hmm, is there an issue with not reaching `serverSocket.accept()`?

Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: However, it wouldn't hurt to simply the code at the expense of a little bit of imprefection, given the code is only for testing. After all, theoretically I am guessing the server will not respond while it is serving a client, so I think it is still not perfect anyway.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java (hunk 7 above)
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: But you could be also right. It'd be interesting to test closing `OutputStream` first on Windows.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java [hunk 8]
```diff
@@ -0,0 +1,79 @@
...
+
+/** Simple local web server for testing. */
+public class TestWebServer implements Closeable {
+
+  private final ServerSocket serverSocket;
+  private final List<Socket> sockets = new ArrayList<>();
+
+  public TestWebServer() throws IOException, InterruptedException {
+    serverSocket = new ServerSocket(0);
+    new Thread(this::serve200).start();
```
Comment (coollog) [inline jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: An alternative here would be to do `Executors.newSingleThreadExecutor().submit(this::serve200);` and change `serve200` to `private Void serve200() throws IOException` to remove the empty `catch`.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java (hunk 7 above)
Comment (coollog) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: Actually, nevermind, the try-with-resource closes resources with the reverse order of creation.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java [hunk 9]
```diff
@@ -0,0 +1,72 @@
...
+
+  private Void serve200() throws IOException {
+    threadStarted.release();
+    while (true) {
+      Socket socket = serverSocket.accept();
+      socketsToClose.add(socket);
+      try {
+        String response = "HTTP/1.1 200 OK\nContent-Length:12\n\nHello World!\n\n";
+        socket.getOutputStream().write(response.getBytes(StandardCharsets.UTF_8));
+      } catch (IOException ex) {
```
[the remark this answers is not in the document]
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: Good point about flush.

The catch block is needed not to terminate the entire server when an I/O error occurs when responding to some client.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java [hunk 10]
```diff
@@ -0,0 +1,72 @@
...
+    String host = serverSocket.getInetAddress().getHostAddress();
+    return "http://" + host + ":" + serverSocket.getLocalPort();
+  }
+
+  @Override
+  public void close() throws IOException {
+    serverSocket.close();
+    for (Socket socket : socketsToClose) {
+      try (Socket toClose = socket) {
+      } catch (IOException ex) {
```
[the remark this answers is not in the document]
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: Yeah, not a big deal, but this is to continue closing other sockets when closing a certain socket fails. (The exception is thrown when calling `close()` on a socket.)

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java [hunk 11]
```diff
@@ -0,0 +1,72 @@
...
+      }
+    }
+    executorService.shutdown();
+  }
+
+  private Void serve200() throws IOException {
+    threadStarted.release();
+    while (true) {
+      Socket socket = serverSocket.accept();
+      socketsToClose.add(socket);
```
[the remark this answers is not in the document]
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: It's safe to call `close()` multiple times on a socket or call it on a closed socket. Probably it is safe on almost all `Closeable` classes.

(And I don't think I get the out-of-bound exception. The enhanced `for` loop never throws it.)

[the remark this answers is not in the document]
Comment (coollog) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: Oh sorry I was referring to `TestWebServer#close`, where it loops over the `socketsToClose` non-concurrent list, but this list is being updated (via `add`) in another thread. Perhaps the `executorService.shutdown()` should be called at the start of `TestWebServer#close`.

[the remark this answers is not in the document]
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: Ah, haven't thought about that. Using `ConcurrentLinkedQueue` would make it safe. If `close()` is called concurrently, it may still miss a socket from a running thread, but that's OK.

BTW, I'd like to give a few more final tests on Windows.

[the remark this answers is not in the document]
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: That's a very nice idea.

[the remark this answers is not in the document]
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: Another idea that can close sockets early would be to wait until the client has closed the channel (i.e., checking `InputStream` is still open). However, the current implementation seems to work and enough for testing.

[the remark this answers is not in the document]
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: > wait until the client has closed the channel

Yup, it works. This is definitely the right way. No more weird lazy close, and no need to flush either.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java [hunk 12]
```diff
@@ -0,0 +1,68 @@
...
+  private Void serve200() throws IOException {
+    threadStarted.release();
+    while (true) {
+      try (Socket socket = serverSocket.accept()) {
+        try {
+          String response = "HTTP/1.1 200 OK\nContent-Length:12\n\nHello World!";
+          socket.getOutputStream().write(response.getBytes(StandardCharsets.UTF_8));
+
+          InputStream in = socket.getInputStream();
+          for (int ch = in.read(); ch != -1; ch = in.read()) ;
```
Comment (coollog) [inline jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: Could also do `ByteStreams.copy(socket.getInputStream(), ByteStreams.nullOutputStream());`

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java [hunk 13]
```diff
@@ -0,0 +1,68 @@
...
+
+  String getEndpoint() {
+    String host = serverSocket.getInetAddress().getHostAddress();
+    return "http://" + host + ":" + serverSocket.getLocalPort();
+  }
+
+  @Override
+  public void close() throws IOException {
+    serverSocket.close();
+    executorService.shutdown();
```
Comment (coollog) [inline jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: Should this go before `serverSocket.close()`? I'm thinking if the `serverSocket.close()` is called while line 56 is running, it would throw an exception.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java [hunk 14]
```diff
@@ -0,0 +1,68 @@
...
+  }
+
+  private Void serve200() throws IOException {
+    threadStarted.release();
+    while (true) {
```
Comment (coollog) [inline jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: I'm thinking maybe this web server can just serve one request, since the tests only require that.

File: jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java (hunk 13 above)
Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: That's the point of `serverSocket.close()`, because `accept()` is a blocking call; that is, to terminate the thread.

Also, calling `executorService.shutdown()` doesn't help. It just prevents future scheduling. Generally, it's not possible to kill a thread. `shutdownNow()` can't do it either.

Comment (chanseokoh) [reply jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java]: FYI, the main reason for `shutdown()` is related to terminating JVM: https://stackoverflow.com/questions/29999109/executorservice-jvm-doesnt-terminate
