### PR TITLE
Passes 'docker load' error back to user.

### LINKED ISSUE #330: Better error message from jib:buildDocker when docker command requires sudo
Works fine when the `docker` command does not require sudo. However, the error message is not so helpful when it does.

```
$ docker
...
Run 'docker COMMAND --help' for more information on a command.

$ docker images
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.37/images/json: dial unix /var/run/docker.sock: connect: permission denied

$ mvn -e compile jib:buildDocker
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.447 s
[INFO] Finished at: 2018-05-30T16:12:12-04:00
[INFO] Final Memory: 22M/214M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.1.8-SNAPSHOT:buildDocker (default-cli) on project test-artifact: Build to Docker daemon failed: Broken pipe -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.1.8-SNAPSHOT:buildDocker (default-cli) on project test-artifact: Build to Docker daemon failed
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Build to Docker daemon failed
        at com.google.cloud.tools.jib.maven.BuildDockerMojo.execute(BuildDockerMojo.java:81)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
        at java.security.DigestOutputStream.write(DigestOutputStream.java:145)
        at com.google.cloud.tools.jib.hash.CountingDigestOutputStream.write(CountingDigestOutputStream.java:77)
        at org.apache.commons.compress.utils.CountingOutputStream.write(CountingOutputStream.java:48)
        at org.apache.commons.compress.utils.FixedLengthBlockOutputStream$BufferAtATimeOutputChannel.write(FixedLengthBlockOutputStream.java:241)
        at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.writeBlock(FixedLengthBlockOutputStream.java:92)
        at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.maybeFlush(FixedLengthBlockOutputStream.java:86)
        at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.write(FixedLengthBlockOutputStream.java:122)
        at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.write(TarArchiveOutputStream.java:439)
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:110)
        at com.google.cloud.tools.jib.tar.TarStreamBuilder.lambda$addEntry$0(TarStreamBuilder.java:71)
        at com.google.cloud.tools.jib.tar.TarStreamBuilder.writeEntriesAsTarArchive(TarStreamBuilder.java:57)
        at com.google.cloud.tools.jib.blob.WriterBlob.writeTo(WriterBlob.java:36)
        at com.google.cloud.tools.jib.docker.DockerClient.load(DockerClient.java:83)
        at com.google.cloud.tools.jib.builder.steps.BuildTarballAndLoadDockerStep.afterPushBaseImageLayerFuturesFuture(BuildTarballAndLoadDockerStep.java:118)
        at com.google.common.util.concurrent.CombinedFuture$CallableInterruptibleTask.runInterruptibly(CombinedFuture.java:181)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.io.IOException: This archive contains unclosed entries.
                at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:276)
                at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:293)
                at com.google.cloud.tools.jib.tar.TarStreamBuilder.$closeResource(TarStreamBuilder.java:60)
                at com.google.cloud.tools.jib.tar.TarStreamBuilder.writeEntriesAsTarArchive(TarStreamBuilder.java:60)
                ... 8 more
        Suppressed: java.io.IOException: Stream Closed
                at java.io.FileOutputStream.writeBytes(Native Method)
                at java.io.FileOutputStream.write(FileOutputStream.java:326)
                at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
                at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
                at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
                at com.google.cloud.tools.jib.docker.DockerClient.$closeResource(DockerClient.java:84)
                at com.google.cloud.tools.jib.docker.DockerClient.load(DockerClient.java:84)
                ... 6 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### PR DESCRIPTION
**Pull request by coollog**
Fixes #330 

This exposes the `docker load` error to the user so that they can take action to fix it.

@chanseokoh

### CODE REVIEW

File: jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java [hunk 1]
```diff
@@ -75,13 +75,23 @@ public boolean isDockerInstalled() {
...
     Process dockerProcess = docker("load");
 
     try (OutputStream stdin = dockerProcess.getOutputStream()) {
       imageTarballBlob.writeTo(stdin);
+
+    } catch (IOException ex) {
+      // This error usually happens when docker is not able to connect to the daemon socket.
+      try (InputStreamReader stderr =
+          new InputStreamReader(dockerProcess.getErrorStream(), StandardCharsets.UTF_8)) {
+        String error = CharStreams.toString(stderr);
```
Comment (loosebazooka) [inline jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java]: can 87-89 throw an IOException? If so, we might want to be careful about passing that through to the caller of `load`

Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java]: Yeah, this assumes `IOException` will be errors at the docker application level only (i.e., the docker process knows what the issue was and prints it to stderr). Technically speaking, writing to a process stdin may fail for reasons other than application level failures. For example, the docker process crashing for some unknown reason, docker command-not-found, no executable-bit set on the docker command binary, etc., and in such cases, `dockerProcess.getErrorStream()` may have nothing but the original `IOException` would better describe the situation.

Comment (coollog) [reply jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java]: I reorganized the code a bit and passed the original `IOException` as a cause to the custom generated `IOException` so that it wouldn't be left discarded.

File: jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java [hunk 2]
```diff
@@ -75,13 +109,23 @@ public boolean isDockerInstalled() {
...
    */
-  public String load(Blob imageTarballBlob) throws IOException, InterruptedException {
+  public String load(Blob imageTarballBlob) throws InterruptedException, IOException {
     // Runs 'docker load'.
     Process dockerProcess = docker("load");
 
-    try (OutputStream stdin = dockerProcess.getOutputStream()) {
-      imageTarballBlob.writeTo(stdin);
-    }
+    writeToStdin(
```
Comment (loosebazooka) [inline jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java]: This new method feels like it adds a high cost to readability/code complexity without enough benefit. It feels like we're decoupling the exception handling and method calls in an unnatural way. I would prefer if we kept this simple here (was this for testing)

Comment (coollog) [reply jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java]: Okay, I moved everything back to `load`.

File: jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java [hunk 3]
```diff
@@ -75,13 +75,30 @@ public boolean isDockerInstalled() {
...
+        try (InputStreamReader stderr =
+            new InputStreamReader(dockerProcess.getErrorStream(), StandardCharsets.UTF_8)) {
+          error = CharStreams.toString(stderr);
+
+        } catch (IOException ignored) {
+          // This ignores exceptions from reading stderr and throws the original exception from
+          // writing to stdin.
+          throw ex;
+        }
+        throw new IOException("'docker load' command failed with error: " + error, ex);
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java]: Sorry, late to the party, but why not just
```java
        try (InputStreamReader stderr = ...) {
          String error = CharStreams.toString(stderr);
          throw new IOException("'docker load' command failed with error: " + error, ex);

        } catch (IOException ignored) {
          ...
          throw ex;
        }
```
?

Comment (coollog) [reply jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java]: That would actually catch and ignore the custom `IOException` created after reading the stderr.
