### PR TITLE
Fix V22ManifestListTemplate cast when pulling an oci index manifest

### LINKED ISSUE #3958: buildTar fails with latest Google distroless Java 17 images
**Environment**:

- *Jib version:* 3.3.1
- *Build tool:* maven, 3.6.6
- *OS:* Linux, Ubuntu

```
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 17.0.6, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-67-generic", arch: "amd64", family: "unix"
```

**Description of the issue**:

We updated our base images (hash is the difference) from

`gcr.io/distroless/java17-debian11:nonroot@sha256:3481476327255f2e553415945d9c774dc5936273bf94cfc01509f044da7b3ed5`

to

`gcr.io/distroless/java17-debian11:nonroot@sha256:5154596f58d81687d66c8302face284198caf65033cde6bf6667c488b21745e6`

The maven build fails with

`[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.3.1:buildTar (default-cli) on project spring-boot-k8s-example: class com.google.cloud.tools.jib.image.json.OciIndexTemplate cannot be cast to class com.google.cloud.tools.jib.image.json.V22ManifestListTemplate (com.google.cloud.tools.jib.image.json.OciIndexTemplate and com.google.cloud.tools.jib.image.json.V22ManifestListTemplate are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @2262d6d5) -> [Help 1]
`

**Expected behavior**:

Build passes as before and our application images are build successfully.

**Steps to reproduce**:

  1. Download the spring boot example from this repo
  2. Add the below pom.xml snippet to the jib plugin definition
  3. Run `./mvnw -DskipTestspackage jib:buildTar`

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>jib-maven-plugin</artifactId>
  <version>3.3.1</version>
  <configuration>
    <from>
      <image>gcr.io/distroless/java17-debian11:nonroot@sha256:5154596f58d81687d66c8302face284198caf65033cde6bf6667c488b21745e6</image>
    </from>
  </configuration>
</plugin>
```
**Log output**: 

```
$ ./mvnw -e package jib:buildTar
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< example:spring-boot-k8s-example >-------------------
[INFO] Building spring-boot-k8s-example 0.1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ spring-boot-k8s-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/fziegler/3rd-party/jib/examples/spring-boot/src/main/resources
[INFO] skip non existing resourceDirectory /home/fziegler/3rd-party/jib/examples/spring-boot/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ spring-boot-k8s-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ spring-boot-k8s-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/fziegler/3rd-party/jib/examples/spring-boot/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ spring-boot-k8s-example ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ spring-boot-k8s-example ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:3.1.2:jar (default-jar) @ spring-boot-k8s-example ---
[INFO] 
[INFO] --- jib-maven-plugin:3.3.1:buildTar (default-cli) @ spring-boot-k8s-example ---
[INFO] Tagging image with generated image reference spring-boot-k8s-example:0.1.0. If you'd like to specify a different tag, you can set the <to><image> parameter in your pom.xml, or use the -Dimage=<MY IMAGE> commandline flag.
[WARNING] 'mainClass' configured in 'maven-jar-plugin' is not a valid Java class: ${start-class}
[INFO] 
[INFO] Containerizing application to file at '/home/fziegler/3rd-party/jib/examples/spring-boot/target/jib-image.tar'...
[INFO] Executing tasks:
[INFO] [============                  ] 40.0% complete
[INFO] > building image to tar file
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.439 s
[INFO] Finished at: 2023-03-15T16:08:53+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.3.1:buildTar (default-cli) on project spring-boot-k8s-example: class com.google.cloud.tools.jib.image.json.OciIndexTemplate cannot be cast to class com.google.cloud.tools.jib.image.json.V22ManifestListTemplate (com.google.cloud.tools.jib.image.json.OciIndexTemplate and com.google.cloud.tools.jib.image.json.V22ManifestListTemplate are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @670f2466) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.3.1:buildTar (default-cli) on project spring-boot-k8s-example: class com.google.cloud.tools.jib.image.json.OciIndexTemplate cannot be cast to class com.google.cloud.tools.jib.image.json.V22ManifestListTemplate (com.google.cloud.tools.jib.image.json.OciIndexTemplate and com.google.cloud.tools.jib.image.json.V22ManifestListTemplate are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @670f2466)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:55)
Caused by: org.apache.maven.plugin.MojoExecutionException: class com.google.cloud.tools.jib.image.json.OciIndexTemplate cannot be cast to class com.google.cloud.tools.jib.image.json.V22ManifestListTemplate (com.google.cloud.tools.jib.image.json.OciIndexTemplate and com.google.cloud.tools.jib.image.json.V22ManifestListTemplate are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @670f2466)
    at com.google.cloud.tools.jib.maven.BuildTarMojo.execute (BuildTarMojo.java:159)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:55)
Caused by: java.lang.ClassCastException: class com.google.cloud.tools.jib.image.json.OciIndexTemplate cannot be cast to class com.google.cloud.tools.jib.image.json.V22ManifestListTemplate (com.google.cloud.tools.jib.image.json.OciIndexTemplate and com.google.cloud.tools.jib.image.json.V22ManifestListTemplate are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @670f2466)
    at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.getCachedBaseImages (PullBaseImageStep.java:470)
    at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call (PullBaseImageStep.java:134)
    at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call (PullBaseImageStep.java:71)
    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly (TrustedListenableFutureTask.java:131)
    at com.google.common.util.concurrent.InterruptibleTask.run (InterruptibleTask.java:74)
    at com.google.common.util.concurrent.TrustedListenableFutureTask.run (TrustedListenableFutureTask.java:82)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:833)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Additional Information**: 

The behavior does not occur with the previously mentioned image  (`gcr.io/distroless/java17-debian11:nonroot@sha256:3481476327255f2e553415945d9c774dc5936273bf94cfc01509f044da7b3ed5`) .

There was a change to the image build that moved from docker manifest format to OCI format

```
docker buildx imagetools inspect gcr.io/distroless/java17-debian11:nonroot@sha256:3481476327255f2e553415945d9c774dc5936273bf94cfc01509f044da7b3ed5
Name:      gcr.io/distroless/java17-debian11:nonroot@sha256:3481476327255f2e553415945d9c774dc5936273bf94cfc01509f044da7b3ed5
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:3481476327255f2e553415945d9c774dc5936273bf94cfc01509f044da7b3ed5
           
Manifests: 
  Name:      gcr.io/distroless/java17-debian11:nonroot@sha256:8d3f355ee92b8da899db8739ad994740cace766fa5c22abce49ba242657157f2
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64
             
  Name:      gcr.io/distroless/java17-debian11:nonroot@sha256:01022fc221d78827d9d2f7d021eaad6705e50b1983fe04e45606c75758b72ed0
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64
             
  Name:      gcr.io/distroless/java17-debian11:nonroot@sha256:b4de50145c10fed2067f1125ab7bdc0dd5468afa0e27807e01c5e86145d1289c
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/ppc64le
             
  Name:      gcr.io/distroless/java17-debian11:nonroot@sha256:b337804c4852f00ff55277c44c889bcf352384082e61bb557bfb61f0d56c8f68
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/s390x
```

```
docker buildx imagetools inspect gcr.io/distroless/java17-debian11:nonroot@sha256:5154596f58d81687d66c8302face284198caf65033cde6bf6667c488b21745e6
Name:      gcr.io/distroless/java17-debian11:nonroot@sha256:5154596f58d81687d66c8302face284198caf65033cde6bf6667c488b21745e6
MediaType: application/vnd.oci.image.index.v1+json
Digest:    sha256:5154596f58d81687d66c8302face284198caf65033cde6bf6667c488b21745e6
           
Manifests: 
  Name:      gcr.io/distroless/java17-debian11:nonroot@sha256:4f1f85307f592125bae41a366e62e9c0e7c916e053854004b3acf1cbf7c726e4
  MediaType: application/vnd.oci.image.manifest.v1+json
  Platform:  linux/amd64
             
  Name:      gcr.io/distroless/java17-debian11:nonroot@sha256:b3fb74abd29a0a15b6a96f0ce3b1b10fe8cd659f5b3a34a68eda7940901a7cc2
  MediaType: application/vnd.oci.image.manifest.v1+json
  Platform:  linux/arm64
             
  Name:      gcr.io/distroless/java17-debian11:nonroot@sha256:33fdfda1fb7c109ea3cfa239ad37a1d4545e7fc3ce08a8d9592f5054882640b5
  MediaType: application/vnd.oci.image.manifest.v1+json
  Platform:  linux/s390x
             
  Name:      gcr.io/distroless/java17-debian11:nonroot@sha256:0616be507c506457ba61a5204595860a4709b9c7e665d35173172d4bbe7cf8bc
  MediaType: application/vnd.oci.image.manifest.v1+json
  Platform:  linux/ppc64le
```

See this commit:

https://github.com/GoogleContainerTools/distroless/commit/fb94acc429d87523020a0a801446f178708e2a10

### PR DESCRIPTION
**Pull request by rquinio**
Fixes #3958

Since there's no more downcast in PullBaseImageStep of manifest lists actual implementation, use the parent class in the unit tests.
Also update jib-core gradle example to compile with 0.23.0.

I was able to reproduce via a gradle build using jib-core (from: gcr.io/distroless/java17-debian11:nonroot@sha256:5154596f58d81687d66c8302face284198caf65033cde6bf6667c488b21745e6)  and verify the fix works. Though I'm not sure why the issue wasn't caught by the new integration test cases added in #3965 ?

Before filing a pull request, make sure to do the following:

- [x] Create a new issue at https://github.com/GoogleContainerTools/jib/issues/new/choose.
- [x] Ensure that your implementation plan is approved by the team.
- [x] Verify that integration tests and unit tests are passing after the change.
- [x] Address all checkstyle issues. Refer to the [style guide](https://github.com/GoogleContainerTools/jib/blob/0ed7dca36864b6b19ff61629fc578018041fa15f/STYLE_GUIDE.md#style-guide).

This helps to reduce the chance of having a pull request rejected.

### CODE REVIEW

File: jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStepTest.java [hunk 1]
```diff
@@ -457,15 +463,15 @@ public void testGetCachedBaseImages_v22ManifestListCached_partialMatches()
   }
 
   @Test
-  public void testGetCachedBaseImages_v22ManifestListCached_onlyPlatforms()
+  public void testGetCachedBaseImages_nanifestListCached_onlyPlatforms()
```
Comment (emmileaf) [inline jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStepTest.java:466]:
```suggestion
  public void testGetCachedBaseImages_manifestListCached_onlyPlatforms()
```

**Review by emmileaf — APPROVED** [review]
Just one small typo typo fix, otherwise LGTM. Thank you for the contribution! 

On your note about integration tests, I think the ones added in https://github.com/GoogleContainerTools/jib/pull/3965 didn't catch this issue because it is in the caching logic and will not be reached (and fail) on the first time pulling. It would be nice to have additional coverage in the integration tests for this (perhaps by having a test using `OciIndexTemplate` that pulls twice and forces cache with `Djib.alwaysCacheBaseImage=true`?), but not a blocker for merging this fix.

**Comment by rquinio** [comment]
Regarding the integration test I've realized ManifestPullerIntegrationTest only tests the RegistryClient, not the actual Jib build steps.
I think it's missing a case in JibIntegrationTest that would pull an oci index.
Today it's targeting only docker.io busybox image which is a V22 Manifest list. 
I'll have a look later in the week.

**Comment by rquinio** [comment]
I've added a test case to JibIntegrationTest, which was failing before the fix.

**Comment by emmileaf** [comment]
Awesome, thank you @rquinio for the fix and improvement to test coverage!
