### PR TITLE
For config generation use create and move of temp file

### LINKED ISSUE #2294: Warning from empty global Jib config
I first observed this in this [log](https://github.com/GoogleContainerTools/jib/pull/2264#issuecomment-583288030).

I also hit this on Windows:
```
[WARNING] Failed to read global Jib config: No content to map due to end-of-input
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 0]; you may need to fix or delete C:\Users\chanseok\AppData\Local\Google\Jib\Config\config.json;
```
The code for this is in [`UpdateChcker.java`](https://github.com/GoogleContainerTools/jib/blob/master/jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java#L116).

In my case, the config file (`config.json`) is empty (0-byte). I think it's easy to generate an empty file.

First, we need to understand when and why we may create an empty file. ~~And if it seems not possible to prevent that, we should find a way to suppress this warning.~~ Turns out, we never intended to create an empty file and doing so is a bug that wipes out the values set by the user. We should never let this happen.

### PR DESCRIPTION
**Pull request by loosebazooka**
I think this is the minimum fix, but I went back and forth on creating a config class that does the config work potentially making it easier to test? (I think?) I'll post that as a followup but this should do:
fixes #2294

### CODE REVIEW

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java [hunk 1]
```diff
@@ -123,11 +127,24 @@ void setDisableUpdateCheck(boolean disableUpdateCheck) {
         // Generate config file if it doesn't exist
         ConfigJsonTemplate config = new ConfigJsonTemplate();
         Files.createDirectories(configDir);
-        try (OutputStream outputStream = Files.newOutputStream(configFile)) {
+        Path temp = configDir.resolve(CONFIG_FILENAME + ".tmp");
```
Comment (chanseokoh) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java]: `temp` --> `tempConfigFile`

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java [hunk 2]
```diff
@@ -123,11 +127,24 @@ void setDisableUpdateCheck(boolean disableUpdateCheck) {
...
+          // Attempts an atomic move first, and falls back to non-atomic if the file system does not
+          // support atomic moves.
+          try {
+            Files.move(
+                temp,
+                configFile,
+                StandardCopyOption.ATOMIC_MOVE,
+                StandardCopyOption.REPLACE_EXISTING);
+          } catch (AtomicMoveNotSupportedException ignored) {
+            Files.move(temp, configFile, StandardCopyOption.REPLACE_EXISTING);
```
Comment (chanseokoh) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java]: I think we don't need to do this manually. I believe `Files.move` will do this fallback.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java [hunk 3]
```diff
@@ -123,11 +127,24 @@ void setDisableUpdateCheck(boolean disableUpdateCheck) {
...
+          }
         } catch (IOException ex) {
           // If attempt to generate new config file failed, delete so we can try again next time
           log.accept(LogEvent.debug("Failed to generate global Jib config; " + ex.getMessage()));
+          Files.deleteIfExists(temp);
           Files.deleteIfExists(configFile);
```
Comment (chanseokoh) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java]: There's one problem with this. If `Files.move` fails, the existing and working config file will be deleted. I think we can just remove `Files.deleteIfExists()` if we are moving the temp file rather than directly replacing the original file. No need to touch the exist one ever. And it's not a big deal not to delete the temp file. It will be extremely rare that moving will fail, and if that happens, the presence of a `.tmp` file may give more clues, I guess?

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java (hunk 2 above)
Comment (loosebazooka) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java]: We do this in a few places..? CacheStorageWriter mostly? but that could be an artifact from before we knew what was happening? https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorageWriter.java#L140

Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java]: Ah, sorry. Now you said it. I think this makes sense. `AtomicMoveNotSupportedException` is expected because we use the `ATOMIC_MOVE` option.

So perhaps doing `Files.move` without `ATOMIC_MOVE` is sufficient. But honestly I don't have confidence.

Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java]: Let's keep the current code? At least it seems safe.

Comment (loosebazooka) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java]: Which current code? This or the code before this PR?

Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java]: Sorry, the PR with two `Files.move()` that we also do in other places.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java (hunk 3 above)
Comment (loosebazooka) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java]: hrmm.. so I removed this for the regular config file, but I left in the temp file removal, maybe I should leave that in?
