### PR TITLE
ci: update integration tests that expect docker manifest format from distroless image

### LINKED ISSUE #3963: Fix integration tests that use latest distroless image and expect docker manifest format
With the recent distroless image switch to OCI-format manifests, Jib's integration testing breaks where `gcr.io/distroless/base:latest` is used in docker-format manifest-related testing. Opening this issue to track updating this where affected across the test suite.

https://github.com/GoogleContainerTools/jib/blob/e50b825cfe92f0bc3a690de40444485e6fae51e2/jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java#L44-L45

Example from logs:

```
> Task :jib-core:integrationTest

com.google.cloud.tools.jib.registry.BlobPullerIntegrationTest > testPull FAILED
    com.google.cloud.tools.jib.registry.RegistryErrorException: Tried to pull image manifest for [gcr.io/distroless/base:latest](https://www.google.com/url?q=http://gcr.io/distroless/base:latest&sa=D) but failed because: Manifest with tag 'latest' has media type 'application/vnd.oci.image.index.v1+json', but client accepts 'application/vnd.docker.distribution.manifest.v2+json'.
        at com.google.cloud.tools.jib.registry.RegistryErrorExceptionBuilder.build(RegistryErrorExceptionBuilder.java:101)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.newRegistryErrorException(RegistryEndpointCaller.java:212)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:153)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:114)
        at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:623)
        at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:434)
        at com.google.cloud.tools.jib.registry.BlobPullerIntegrationTest.testPull(BlobPullerIntegrationTest.java:45)

        Caused by:
        com.google.cloud.tools.jib.http.ResponseException: 404 Not Found
        GET [https://gcr.io/v2/distroless/base/manifests/latest](https://www.google.com/url?q=https://gcr.io/v2/distroless/base/manifests/latest&sa=D)
        {"errors":[{"code":"MANIFEST_UNKNOWN","message":"Manifest with tag 'latest' has media type 'application/vnd.oci.image.index.v1+json', but client accepts 'application/vnd.docker.distribution.manifest.v2+json'."}]}
            at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:355)
            at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:266)
            at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:138)
            ... 4 more
```

### PR DESCRIPTION
**Pull request by emmileaf**
Fixes #3963 to unblock CI (See issue for more error details and discussion).

Changes in this PR to address manifest format change in latest distroless image:
- Updates `BlobCheckerIntegrationTest` and `BlobPullerIntegrationTest` by using a fixed older version of the distroless image
- Removes use of “latest” tag in `ManifestPullerIntegrationTest`, and extends it to specifically cover OCI format using pinned image versions

### CODE REVIEW

File: jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java [hunk 1]
```diff
@@ -80,31 +112,41 @@ public void testPull_v22ManifestList() throws IOException, RegistryException {
...
+        RegistryClient.factory(EventHandlers.NONE, "gcr.io", "distroless/base", httpClient)
+            .newRegistryClient();
 
-    // Call to ":latest" targeting a manifest pulls a manifest.
-    V22ManifestTemplate manifestTargeted =
-        registryClient.pullManifest("latest", V22ManifestTemplate.class).getManifest();
-    Assert.assertEquals(2, manifestTargeted.getSchemaVersion());
+    // Ensures call to image at KNOWN_OCI_INDEX_SHA returns an OCI index
+    OciIndexTemplate manifestListTargeted =
+        registryClient.pullManifest(KNOWN_OCI_INDEX_SHA, OciIndexTemplate.class).getManifest();
```
Comment (emmileaf) [inline jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java:140]: Alt: instead of `KNOWN_OCI_INDEX_SHA`, this test can keep using the "latest" tag (which keeps it susceptible for breakage but able to detect future changes in this image, as noted in https://github.com/GoogleContainerTools/jib/issues/3963#issuecomment-1481405637).

File: jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java [hunk 2]
```diff
@@ -65,13 +79,31 @@ public void testPull_v21() throws IOException, RegistryException {
   @Test
   public void testPull_v22() throws IOException, RegistryException {
     RegistryClient registryClient =
-        RegistryClient.factory(EventHandlers.NONE, "gcr.io", "distroless/java", httpClient)
+        RegistryClient.factory(EventHandlers.NONE, "gcr.io", "distroless/base", httpClient)
             .newRegistryClient();
```
Comment (mpeddada1) [inline jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java:83]: qq you may have covered this already but why do we need to replace `distroless/java` with `distroless/base`? Is there anything blocking us from using a previous tag from [`gcr.io/distroless/java`](https://pantheon.corp.google.com/gcr/images/distroless/global/java).

Comment (emmileaf) [reply jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java:83]: Mostly for consistency and convenience, since we're already pinning a V22 manifest version of `distroless/base` image for use by `BlobCheckerIntegrationTest` and  `BlobPullerIntegrationTest`. 

If there are concerns with switching the image here, `gcr.io/distroless/java:latest` will actually still work for this test, since it has not been updated since April 2022. So we could also leave this test unchanged, or pin it to that version by SHA. WDYT?

Comment (mpeddada1) [reply jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java:83]: oh gotcha, thank you! Making the base images consistent is a good idea.

File: jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java [hunk 3]
```diff
@@ -80,31 +112,41 @@ public void testPull_v22ManifestList() throws IOException, RegistryException {
...
+        registryClient.pullManifest(KNOWN_OCI_INDEX_SHA, OciIndexTemplate.class).getManifest();
+    Assert.assertEquals(2, manifestListTargeted.getSchemaVersion());
+    Assert.assertTrue((manifestListTargeted.getManifests().size() > 0));
+
+    // Generic call to image at KNOWN_OCI_INDEX_SHA, should also return an OCI index
+    ManifestTemplate manifestListGeneric =
+        registryClient.pullManifest(KNOWN_OCI_INDEX_SHA).getManifest();
+    Assert.assertEquals(2, manifestListGeneric.getSchemaVersion());
+    MatcherAssert.assertThat(manifestListGeneric, CoreMatchers.instanceOf(OciIndexTemplate.class));
+    Assert.assertTrue(((OciIndexTemplate) manifestListGeneric).getManifests().size() > 0);
```
Comment (mpeddada1) [inline jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java:149]: nit: Perhaps we can use Truth here?

File: jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java [hunk 4]
```diff
@@ -80,31 +112,41 @@ public void testPull_v22ManifestList() throws IOException, RegistryException {
         RegistryClient.factory(EventHandlers.NONE, "gcr.io", "distroless/base", httpClient)
             .newRegistryClient();
 
-    // Ensure ":latest" is a manifest list
+    // Ensures call to image at KNOWN_MANIFEST_LIST_SHA returns a manifest list
```
Comment (mpeddada1) [inline jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java:115]: minor: how about we say something like "at the specified sha`? This can prevent the comment from becoming stale if the variable name changes.

**Review by mpeddada1 — APPROVED** [review]
Thanks @emmileaf! Left some minor comments but otherwise LGTM!

File: jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java (hunk 4 above)
Comment (emmileaf) [reply jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java]: Makes sense, updated!

**Review by mpeddada1 — APPROVED** [review]
