### PR TITLE
#3158 - [Jib core] Tar archives with same contents are not reproducible

### LINKED ISSUE #3158: [Jib core] Tar archives with same contents are not reproducible
**Environment**:

- *Jib version:*  v0.18.0-core
- *Build tool:* Gradle 6.01
- *OS:* macOS 10.15.7

**Description of the issue**:
I create a tar file from a registry image.
`Jib.from(RegistryImage.named(image)).containerize(Containerizer.to(TarImage.at(outputPath).named(image)));`

This is being executed as part of a bazel genrule, with the tar file as the output.  We discovered that if this is rerun, the tar file created is different when using the same inputs, run on the same machine but at a later time.

**Expected behavior**:
We expect the tar file to be identical if the inputs have not changed.

**Steps to reproduce**:

  1.  Create tar file using Jib as above
  2. Rename the tar file output.tar
  3. Wait 5 seconds, and create another tar file using Jib as above, rename the tar output2.tar
  4. shassum -a 256 output.tar
  5. shassum -a 256 output2.tar

**Additional Information**: 
The issue is due to TarStreamBuilder creating blobs using new TarArchiveEntry(name)
By default this sets the mod time of the blob to be current time, thus making the resulting Tar image not reproducible.

`this.modTime = new Date().getTime() / MILLIS_PER_SECOND;`

#3159 3159

### PR DESCRIPTION
**Pull request by davidtron**
Fixes #3158.

Sets the mod time on TarArchiveEntry to DEFAULT_MODIFICATION_TIME (Epoch second 1) in order to create reproducible Tar images. Associated unit test creates 2 tars output streams from the same input 2 seconds apart to show the failure if we don't explicitly set the TarArchiveEntry mod time

### CODE REVIEW

**Comment by loosebazooka** [comment]
I think this might be working as intended. Where are you encountering this as an issue that needs to be fixed? ReproducibleLayerBuilder adds in the behavior of reproducibility.

**Comment by davidtron** [comment]
The problem occurs when I create a Tar file using Jib
`Jib.from(RegistryImage.named(image)).containerize(Containerizer.to(TarImage.at(outputPath).named(image)));`
I've put the steps to reproduce the issue #3158 and an example unit test that will fail without the proposed change to set the tar modtime to a fixed time.

My question is - should Jib produce a reproducible tar file when the input files are the same but the command has been run at a different time?

**Comment by loosebazooka** [comment]
Ah okay, I see. 

I think this needs to be solved in ImageTarBall's calls to TarStreamBuilder (#addByteEntry and #addBlobEntry). Those methods should be setting the timestamp you want on the entries.

@chanseokoh does that make sense?

File: jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java [hunk 1]
```diff
@@ -89,6 +91,7 @@ public void addByteEntry(byte[] contents, String name) {
   public void addBlobEntry(Blob blob, long size, String name) {
     TarArchiveEntry entry = new TarArchiveEntry(name);
     entry.setSize(size);
+    entry.setModTime(DEFAULT_MODIFICATION_TIME.getEpochSecond());
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java:94]: I realized that this isn't enough. The `addByteEntry()` above also needs to set the timestamp. Both `addBlobEntry()` and `addByteEntry()` are used in `ImageTarball` to create a tar image stream.

However, we have layers of abstraction in our codebase with a hierarchy, so it doesn't feel right to make `TarStreamBuilder` to get into the business of deciding the timestamp of tar entries. This is a general class to build a tar stream. What I think we should do is to change the signature of the method to `addBlobEntry(Blob blob, long size, String name, Instant modTime)`, and have `ImageTarball` pass in the time.

**Review by chanseokoh — COMMENTED** [review]
Thanks a lot for your contribution! I think we can accept the general direction to reset timestamps. Please check out the comment below.

File: jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java (hunk 1 above)
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java:94]: > I think this needs to be solved in ImageTarBall's calls to TarStreamBuilder (#addByteEntry and #addBlobEntry). Those methods should be allowing a timestamp parameter.

Oh, just realized @loosebazooka already suggested moving this to `ImageTarball` 😂

**Comment by chanseokoh** [comment]
Note for self: CHANGELOG

**Comment by chanseokoh** [comment]
@davidtron just checking in, do you plan to continue the work?

**Comment by davidtron** [comment]
@chanseokoh yes just updated the code to pull up to ImageTarball as suggested

File: jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageTarball.java [hunk 2]
```diff
@@ -48,6 +49,7 @@
   private final Image image;
   private final ImageReference imageReference;
   private final ImmutableSet<String> allTargetImageTags;
+  private final Instant creationTime = Instant.EPOCH;
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageTarball.java:52]:
```suggestion
  private static final Instant TAR_ENTRY_MODIFICATION_TIME = Instant.EPOCH;
```
and move the field up.

File: jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java [hunk 3]
```diff
@@ -71,10 +72,12 @@ public void addTarArchiveEntry(TarArchiveEntry entry) {
    *
    * @param contents the bytes to add to the tarball
    * @param name the name of the entry (i.e. filename)
+   * @param modTime the time the entry is created
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java:75]:
```suggestion
   * @param modificationTime the modification time of the entry
```

File: jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java [hunk 4]
```diff
@@ -71,10 +72,12 @@ public void addTarArchiveEntry(TarArchiveEntry entry) {
...
    */
-  public void addByteEntry(byte[] contents, String name) {
+  public void addByteEntry(byte[] contents, String name, Instant modTime) {
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java:77]:
```suggestion
  public void addByteEntry(byte[] contents, String name, Instant modificationTime) {
```

File: jib-core/src/test/java/com/google/cloud/tools/jib/tar/TarStreamBuilderTest.java [hunk 5]
```diff
@@ -46,6 +47,7 @@
   private byte[] fileAContents;
   private byte[] fileBContents;
   private TarStreamBuilder testTarStreamBuilder = new TarStreamBuilder();
+  private final Instant creationTime = Instant.EPOCH;
```
Comment (chanseokoh) [inline jib-core/src/test/java/com/google/cloud/tools/jib/tar/TarStreamBuilderTest.java:50]:
```suggestion
```

File: jib-core/src/test/java/com/google/cloud/tools/jib/tar/TarStreamBuilderTest.java [hunk 6]
```diff
@@ -96,10 +98,11 @@ public void testToBlob_stringsAndTarArchiveEntriesWithCompression() throws IOExc
...
   @Test
   public void testToBlob_multiByte() throws IOException {
-    testTarStreamBuilder.addByteEntry("日本語".getBytes(StandardCharsets.UTF_8), "test");
-    testTarStreamBuilder.addByteEntry("asdf".getBytes(StandardCharsets.UTF_8), "crepecake");
+    testTarStreamBuilder.addByteEntry("日本語".getBytes(StandardCharsets.UTF_8), "test", creationTime);
+    testTarStreamBuilder.addByteEntry(
+        "asdf".getBytes(StandardCharsets.UTF_8), "crepecake", creationTime);
     testTarStreamBuilder.addBlobEntry(
-        Blobs.from("jib"), "jib".getBytes(StandardCharsets.UTF_8).length, "jib");
+        Blobs.from("jib"), "jib".getBytes(StandardCharsets.UTF_8).length, "jib", creationTime);
```
Comment (chanseokoh) [inline jib-core/src/test/java/com/google/cloud/tools/jib/tar/TarStreamBuilderTest.java:105]: In tests, just do
```suggestion
        Blobs.from("jib"), "jib".getBytes(StandardCharsets.UTF_8).length, "jib", Instant.EPOCH);
```

**Review by chanseokoh — COMMENTED** [review]
Thanks!

Can you add some tests? I think its' not difficult to do so in `TarStreamBuilderTest`, as I see other tests open a tar and go over `TarArchiveEntry`?

**Comment by davidtron** [comment]
Just updating the test, I found that when we add a TarEntry to TarStreamBuilder we don't manipulate the time, instead rely on the fact that ReproducibleLayerBuilder which delegates to UniqueTarArchiveEntries to manage the mod time.

File: jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java [hunk 7]
```diff
@@ -71,10 +72,12 @@ public void addTarArchiveEntry(TarArchiveEntry entry) {
    *
    * @param contents the bytes to add to the tarball
    * @param name the name of the entry (i.e. filename)
+   * @param modificationTime the modification time of the entry
    */
-  public void addByteEntry(byte[] contents, String name) {
+  public void addByteEntry(byte[] contents, String name, Instant modificationTime) {
     TarArchiveEntry entry = new TarArchiveEntry(name);
     entry.setSize(contents.length);
+    entry.setModTime(modificationTime.getEpochSecond());
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java:80]: Shouldn't this be `toEpochMillis()`? I guess writing a test will confirm it.

**Review by chanseokoh — COMMENTED** [review]
Again, thanks for your contribution!

`TarStreamBuilder` is completely independent of `ReproducibleLayerBuilder`, so no need to bring that into your thinking. It's just that `addTarArchiveEntry(TarArchiveEntry)` accepts a fully-built tar entry as-is (we should not manipulate the entry at all). OTOH, the other add methods internally create a new tar entry with the given properties, so it's only natural to set those properties.

So I'm not exactly sure how you're writing tests, but you can test all of them to check if they all work in the intended way. If `addTarArchiveEntry(TarArchiveEntry)` adds an entry whose modTime is set to 2021-04-09, then you can just check if the result tar archive has the very entry with the same modTime?

File: jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java (hunk 7 above)
Comment (davidtron) [reply jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java:80]: Hi @chanseokoh the tests are in the unit test `TarStreamBuilderTest`
You are quite right it should be passed in using `toEpochMillis` because the implementation of TarArchiveEntry divides whats passed in by 1000.  I've updated the unit test to set an explicit time rather than the Epoch to catch that, and show that the expected time is `MODIFICATION_TIME.truncatedTo(SECONDS)`

Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java:80]: I don't see the changes. Forgot to push a new commit?

**Review by chanseokoh — APPROVED** [review]
Thanks for your contribution!

I actually wanted to have separate and dedicated unit tests, but given the back-and-forth, I can take care of it after merging this.
