### PR TITLE
Fixes Jib task dependency on classes.

### LINKED ISSUE #374: 'classes' dependency should be handled after project evaluation
Currently if the java plugin is applied after the jib plugin, builds will fail due to error:
```
A problem occurred evaluating root project 'hello-gradle'.
> Failed to apply plugin [id 'com.google.cloud.tools.jib']
   > Task with path 'classes' not found in root project 'hello-gradle'.
```

### PR DESCRIPTION
**Pull request by coollog**
Fixes #374

### CODE REVIEW

File: jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java [hunk 1]
```diff
@@ -32,23 +32,29 @@ public void apply(Project project) {
...
+            .setJibExtension(jibExtension);
+    Task buildDockerTask =
+        project
+            .getTasks()
+            .create("jibBuildDocker", BuildDockerTask.class)
+            .setJibExtension(jibExtension);
+
+    // Has all tasks depend on the 'classes' task.
+    project.afterEvaluate(
+        ignored -> {
```
Comment (loosebazooka) [inline jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java]: I wonder if the project object in the afterEvaluate block has different properties than the one calling afterEvaluate?

Comment (loosebazooka) [reply jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java]: the one we've `ignored`

Comment (coollog) [reply jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java]: Hmm, okay I'll change to use the one that was ignored.
