### PR TITLE
Fix progress bar logger for Gradle

### LINKED ISSUE #1963: Log output gets overwritten
Jib output used to say:
```
Containerizing application to Docker daemon as test...

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, Hello]

Built image to Docker daemon as test
Executing tasks:
[==============================] 100.0% complete
```

but now the first two messages get overwritten shortly after printing them, and the final output becomes:

```




Built image to Docker daemon as test
Executing tasks:
[==============================] 100.0% complete
```

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #1963.

#1963 was a regression introduced in #1953 that fixed a logging issue in Maven. But it broke Gradle.

Unfortunately, I can't think of a better and safer way than to maintain two separate paths for Maven and Gradle. I restored the original trick to fix the Gradle issue.

### CODE REVIEW

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooter.java [hunk 1]
```diff
@@ -103,13 +116,16 @@ public void log(Level logLevel, String message) {
 
     singleThreadedExecutor.execute(
         () -> {
-          if (eraseFooter()) {
-            // If a previous footer was erased, the message needs to go up a line. However, we go up
-            // two lines (and then down one line by calling "accept()" once) to correct an issue in
-            // Maven: https://github.com/GoogleContainerTools/jib/issues/1952
+          boolean didErase = eraseFooter();
```
Comment (TadCordle) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooter.java]: L119-126 and L152-159 are the same, I wonder if we can pull those lines into `eraseFooter()`.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/ConsoleLoggerBuilder.java [hunk 2]
```diff
@@ -39,11 +39,15 @@
    *
    * @param singleThreadedExecutor a {@link SingleThreadedExecutor} to ensure that all messages are
    *     logged in a sequential, deterministic order
+   * @param mavenFix fixes logging issue in Maven
+   *     (https://github.com/GoogleContainerTools/jib/issues/1952)
    * @return a new {@link ConsoleLoggerBuilder}
    */
-  public static ConsoleLoggerBuilder rich(SingleThreadedExecutor singleThreadedExecutor) {
+  public static ConsoleLoggerBuilder rich(
+      SingleThreadedExecutor singleThreadedExecutor, boolean mavenFix) {
```
Comment (TadCordle) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/ConsoleLoggerBuilder.java]: I don't know about this parameter name, maybe we should just have two different `richGradle` and `richMaven` methods instead of passing in a `boolean`. Although I'm not sure if I really like that more. It at least sounds less hacky (then again I guess this is a bit of a hack, and maybe we shouldn't try to hide that).

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooter.java (hunk 1 above)
Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooter.java]: Yeah, the code is duplicated, but I find the logic of the duped code is a bit weird to shove into `eraseFooter()` for the sake of removing redundancy. The caller is expected to follow up with doing the correct thing after calling `eraseFooter()`(i.e., must print the next message with the returned prefix), so I don't quite like it from the API perspective. I think this amount of dup is not worse than that.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/ConsoleLoggerBuilder.java (hunk 2 above)
Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/ConsoleLoggerBuilder.java]: Yeah, agreed. Kinda expected this reaction. I wanted to avoid putting a specific builder name, since theoretically we may have more builders in the future. I think I just came up with a much better name: `enableTwoCursorUpJump`. The rich console is all about the hacky cursor trick, so this kind of console-controlling flag names for the constructor method sound pretty natural to me.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooter.java [hunk 3]
```diff
@@ -103,13 +116,16 @@ public void log(Level logLevel, String message) {
...
+
+          // If a previous footer was erased, the message needs to go up a line. But only do so when
+          // not doing the two-cursor-up fix.
+          String prefix = didErase && !enableTwoCursorUpJump ? CURSOR_UP_SEQUENCE : "";
```
Comment (TadCordle) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooter.java]: Maybe personal preference, but I think the shorter code here is harder to follow than just separating each condition fully.
```
if (didErase) {
  if (enableTwoCursorUpJump) {
    messageConsumer.accept(String.format(CURSOR_UP_SEQUENCE_TEMPLATE, 2));
    messageConsumer.accept(message);
  } else {
    messageConsumer.accept(CURSOR_UP_SEQUENCE + message);
  }
} else {
  messageConsumer.accept(message);
}
```

Unfortunately that leads to even more duplication.

Comment (chanseokoh) [reply jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooter.java]: Yeah, that's true. Expanded the code.
