### PR TITLE
Better error message when using invalid image reference format

### LINKED ISSUE #1577: Better actionable error message on InvalidImageReferenceException: Invalid image reference
**Description of the issue**:
An uncheckedException, InvalidImageReferenceException, when pushing to an gcr

**Expected behavior**:
Should be able to successfully push new image to remote gcr

**Steps to reproduce**: 
* add the jib gradle plugin
* configure the jib plugin to push image to gcr
* run a gradle jib

**Environment**: 
Gradle, MacOS

**`jib-gradle-plugin` Configuration**: 
```groovy
jib{
    from{
        image = 'openjdk:11-jre-slim'
    }
    to{
        image = "gcr.io/****/$rootProject.name"
    }
    container{
        jvmFlags = ['-Xdebug']
        ports = ['8181']
    }
}
```

```
Caused by: org.gradle.internal.UncheckedException: com.google.cloud.tools.jib.image.InvalidImageReferenceException: Invalid image reference: gcr.io/***/my_app_name
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:67)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:106)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:672)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$4.run(ExecuteActionsTaskExecuter.java:338)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:327)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:312)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:15
```

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #1577.

### CODE REVIEW

File: jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java [hunk 1]
```diff
@@ -169,6 +169,10 @@ public void buildDocker()
           HelpfulSuggestions.forIncompatibleBaseImageJavaVesionForGradle(
               ex.getBaseImageMajorJavaVersion(), ex.getProjectMajorJavaVersion()),
           ex);
+
+    } catch (InvalidImageReferenceException ex) {
```
Comment (TadCordle) [inline jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java]: At some point I think we should try reducing the copy-pasted exception handling between each of the tasks/goals.

File: jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/HelpfulSuggestions.java [hunk 2]
```diff
@@ -75,6 +75,14 @@ public static String forIncompatibleBaseImageJavaVesionForMaven(
             + " or below");
   }
 
+  public static String forInvalidImageReference(String reference) {
+    return suggest(
+        "Invalid image reference " + reference,
+        "check that the reference is formatted correctly according to "
+            + "https://docs.docker.com/engine/reference/commandline/tag/#extended-description "
```
Comment (TadCordle) [inline jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/HelpfulSuggestions.java]: Maybe some punctuation or a newline after this url

File: jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java (hunk 1 above)
Comment (chanseokoh) [reply jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java]: Yeah, that's a sound idea.
