### PR TITLE
[Jib CLI] fix concurrency issue with --http-trace

### LINKED ISSUE #3156: [Jib CLI] --http-trace sometimes doesn't work
The behavior is very unpredictable. That makes me suspect a concurrency issue. And it seems to always work with `--serialize`.

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #3156.

I am not able to reproduce the issue with this fix.

### CODE REVIEW

File: jib-cli/src/main/java/com/google/cloud/tools/jib/cli/JibCli.java [hunk 1]
```diff
@@ -33,6 +34,7 @@
 public class JibCli {
 
   static Logger configureHttpLogging(Level level) {
+    new ApacheHttpTransport(); // fixes https://github.com/GoogleContainerTools/jib/issues/3156
```
Comment (mpeddada1) [inline jib-cli/src/main/java/com/google/cloud/tools/jib/cli/JibCli.java:37]: Let's add a small comment to detail what this does? Something like, "to initialize a static logger field.."

**Review by mpeddada1 — APPROVED** [review]
