### PR TITLE
Fix root progress construction

### LINKED ISSUE #1796: Test failure about root progress dispatch
This looks like a flaky test, but I don't remember having seen this. It means the progress event dispatched more completion than the total expected. It's concerning, so I'll dig into it.

```
    * What went wrong:
    Execution failed for task ':jibDockerBuild'.
    > Progress exceeds max for 'building image to Docker daemon': 1 more beyond 5

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 4s
    3 actionable tasks: 3 executed
        at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:237)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:234)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:298)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:234)
        at com.google.cloud.tools.jib.gradle.TestProject.build(TestProject.java:82)
        at com.google.cloud.tools.jib.gradle.JibRunHelper.buildToDockerDaemon(JibRunHelper.java:96)
        at com.google.cloud.tools.jib.gradle.EmptyProjectIntegrationTest.testDockerDaemon_userNames(EmptyProjectIntegrationTest.java:112)
```

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #1796.

I missed that the root progress tree should be created in the main thread. (`newChildProducer()` should not be called in child threads.)

### CODE REVIEW

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcher.java [hunk 1]
```diff
@@ -147,7 +147,7 @@ public void dispatchProgress(long progressUnits) {
   private long decrementRemainingAllocationUnits(long units) {
     Preconditions.checkState(!closed);
 
-    if (remainingAllocationUnits > units) {
+    if (remainingAllocationUnits >= units) {
```
Comment (chanseokoh) [inline jib-core/src/main/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcher.java]: Note: this is unrelated to #1796 and does not change the behavior. (If they are same, the remaining units become 0.) I just think `>=` looks more intuitive.

Comment (TadCordle) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcher.java]: To me `>=` immediately followed by the subtraction looks less intuitive, but it's small.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java [hunk 2]
```diff
@@ -241,7 +239,7 @@ private void writeTarFile(Path outputPath) {
             () ->
                 new WriteTarFileStep(
                         buildConfiguration,
-                        childProgressDispatcherFactorySupplier.get(),
+                        childProgressDispatcherFactories.pop(),
```
Comment (loosebazooka) [inline jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java]: what am I missing here? Why can't this call just be: progressEventDispatcher.newChildProducer() ?

Comment (TadCordle) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java]: It sounds like `newChildProducer()` shouldn't be called in separate threads, so we need to create them all in the main thread first and then pass them to each step when they run.

Comment (loosebazooka) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java]: Either way, I find this mechanism a little strange. Why not just keep a reference to progressEventDispatcher instead of pre-generating children?

Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java]: For this scheduling, if we just do `progressEventDispatcher.newChildProducer()`, it will not be called immediately because it is wrapped in a runnable as `() -> ... progressEventDispatcher.newChildProducer() ...`. Here, the main thread should create child producers and construct the tree properly.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcher.java (hunk 1 above)
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcher.java]: That may be true if you look at this condition and the true branch, but I found it difficult to digest the false branch if the remaining units are equal to the units to subtract.

File: jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java (hunk 2 above)
Comment (chanseokoh) [reply jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java]: You were right @loosebazooka. I can directly call `progressEventDispatcher.newChildProducer()`; just need to do it at the beginning.
